NorthstarCity_House2_MapScripts::
	.byte 0

NorthstarCity_House2_Boy::
	msgbox NorthstarCity_House2_Text_Boy, MSGBOX_NPC
	end

NorthstarCity_House2_Woman::
	msgbox NorthstarCity_House2_Text_Woman, MSGBOX_NPC
	end

NorthstarCity_House2_Text_Boy:
	.string "{COLOR}{BLUE}I don't reminisce over yesterday,\n"
	.string "I don't think about tomorrow.\p"
	.string "I only live today to the fullest.\n"
	.string "That's my policy!$"

NorthstarCity_House2_Text_Woman:
	.string "{COLOR}{RED}Pokémon…\n"
	.string "People…\p"
	.string "It's only natural that we are all so\n"
	.string "very different.\p"
	.string "Make sure that you never judge a\n"
	.string "Pokémon on if it's weak or strong.\p"
	.string "You must always look for the good\n"
	.string "inside of them. That's what counts!$"
