UnionCity_Interlink_MapScripts::
	.byte 0

UnionCity_Interlink_Little_Girl::
	msgbox UnionCity_Interlink_Text_Little_Girl, MSGBOX_NPC
	end

UnionCity_Interlink_Boy::
	msgbox UnionCity_Interlink_Text_Boy, MSGBOX_NPC
	end

UnionCity_Interlink_Psychic::
	msgbox UnionCity_Interlink_Text_Psychic, MSGBOX_NPC
	end

UnionCity_Interlink_Grandma::
	msgbox UnionCity_Interlink_Text_Grandma, MSGBOX_NPC
	end

UnionCity_Interlink_Text_Little_Girl:
	.string "{COLOR}{RED}I'm tired of playing in Union City, but\n"
	.string "this is as far as Mom lets me go…\p"
	.string "She says Route 2 is full of dangerous\n"
	.string "Pokémon.$"

UnionCity_Interlink_Text_Boy:
	.string "{COLOR}{BLUE}You seen those Berries that you can\n"
	.string "pick from trees?\p"
	.string "Well, different Berries have different\n"
	.string "effects on your Pokémon.\p"
	.string "Try using one on your Pokémon!$"

UnionCity_Interlink_Text_Psychic:
	.string "{COLOR}{BLUE}Wait, no, don't tell me.\n"
	.string "I can tell just by looking at you.\p"
	.string "You're gonna find many hardships along\n"
	.string "this road, but it'll all be worthwhile.$"

UnionCity_Interlink_Text_Grandma:
	.string "You're telling me you're a Trainer?\n"
	.string "Good grief!\p"
	.string "It seems like you're all starting your\n"
	.string "journeys at a younger age nowadays!\l"
	.string "Be careful out there!$"
