Route4_PokemonDayCare_MapScripts::
	.byte 0

Route4_PokemonDayCare_Boy::
	msgbox Route4_PokemonDayCare_Text_Boy, MSGBOX_NPC
	end

Route4_PokemonDayCare_Text_Boy:
	.string "{COLOR}{BLUE}A Pokémon's nature can be influenced\n"
	.string "if its mother held an Everstone while\l"
	.string "in the Day Care.\p"
	.string "Pokémon with Magma Armor or Flame Body\n"
	.string "shorten the hatching process if they\l"
	.string "are in the party with Eggs."

