LaveriaCity_House4_MapScripts::
	.byte 0

LaveriaCity_House4_OldLady::
	msgbox LaveriaCity_House4_Text_OldLady, MSGBOX_NPC
	end

LaveriaCity_House4_OldMan::
	msgbox LaveriaCity_House4_Text_OldMan, MSGBOX_NPC
	end

LaveriaCity_House4_Text_OldLady:
	.string "Ah, I remember when the Pokémon Center\n"
	.string "was just a humble cottage.\p"
	.string "Healing your Pokémon meant a warm bowl\n"
	.string "of soup by the fire…\p"
	.string "Times have changed, but the joy of\n"
	.string "companionship hasn't.\p"
	.string "Cherish these moments, dear, for they\n"
	.string "are the true treasures of life.$"

LaveriaCity_House4_Text_OldMan:
	.string "As you journey through this icy city,\n"
	.string "remember this…\p"
	.string "Every snowflake, like every Pokémon,\n"
	.string "is unique.\p"
	.string "Embrace the diversity around you, and\n"
	.string "let the cold winds of change shape you\l"
	.string "into the best Trainer you can be.$"
