#ifndef GUARD_CONSTANTS_HEAL_LOCATIONS_H
#define GUARD_CONSTANTS_HEAL_LOCATIONS_H

#define HEAL_LOCATION_NONE 0
#define HEAL_LOCATION_CHANDRA_VILLAGE 1
#define HEAL_LOCATION_SUNRISE_TOWN 2
#define HEAL_LOCATION_UNION_CITY 3
#define HEAL_LOCATION_GREENDALE_VILLAGE 4
#define HEAL_LOCATION_ANHEIM_TOWN 5
#define HEAL_LOCATION_LAVERIA_CITY 6
#define HEAL_LOCATION_HIGHWIND_VILLAGE 7
#define HEAL_LOCATION_NORTHSTAR_CITY 8
#define HEAL_LOCATION_PINLEAF_TOWN 9
#define HEAL_LOCATION_SOOTOPOLIS_CITY 10
#define HEAL_LOCATION_EVER_GRANDE_CITY 11
#define HEAL_LOCATION_OLDALE_TOWN 12
#define HEAL_LOCATION_DEWFORD_TOWN 13
#define HEAL_LOCATION_LAVARIDGE_TOWN 14
#define HEAL_LOCATION_FALLARBOR_TOWN 15
#define HEAL_LOCATION_VERDANTURF_TOWN 16
#define HEAL_LOCATION_PACIFIDLOG_TOWN 17
#define HEAL_LOCATION_EVER_GRANDE_CITY_POKEMON_LEAGUE 18
#define HEAL_LOCATION_SOUTHERN_ISLAND_EXTERIOR 19
#define HEAL_LOCATION_BATTLE_FRONTIER_OUTSIDE_EAST 20
#define HEAL_LOCATION_THYMESGROVE_CITY 21
#define HEAL_LOCATION_PORT_BALINA 22
#define HEAL_LOCATION_WATERWAY_CITY 23
#define HEAL_LOCATION_MOONSPRING_CITY 24
#define HEAL_LOCATION_ZONYA_VILLAGE 25
#define HEAL_LOCATION_DRIFTSTREAM_TOWN 26
#define HEAL_LOCATION_TWILIGHT_VILLAGE 27
#define HEAL_LOCATION_ROUTE14 28
#define HEAL_LOCATION_ROUTE15 29
#define HEAL_LOCATION_MAYHEM_CITY 30
#define HEAL_LOCATION_WEST_DISTRICT 31

#endif // GUARD_CONSTANTS_HEAL_LOCATIONS_H
