#ifndef GUARD_CONSTANTS_MAP_GROUPS_H
#define GUARD_CONSTANTS_MAP_GROUPS_H

//
// DO NOT MODIFY THIS FILE! It is auto-generated from data/maps/map_groups.json
//

// Map Group 0
#define MAP_CHANDRA_VILLAGE   (0 | (0 << 8))
#define MAP_SUNRISE_TOWN      (1 | (0 << 8))
#define MAP_UNION_CITY        (2 | (0 << 8))
#define MAP_GREENDALE_VILLAGE (3 | (0 << 8))
#define MAP_ANHEIM_TOWN       (4 | (0 << 8))
#define MAP_LAVERIA_CITY      (5 | (0 << 8))
#define MAP_HIGHWIND_VILLAGE  (6 | (0 << 8))
#define MAP_NORTHSTAR_CITY    (7 | (0 << 8))
#define MAP_PINLEAF_TOWN      (8 | (0 << 8))
#define MAP_MIRANIA_TOWN      (9 | (0 << 8))
#define MAP_ROUTE1            (10 | (0 << 8))
#define MAP_ROUTE2            (11 | (0 << 8))
#define MAP_ROUTE3            (12 | (0 << 8))
#define MAP_ROUTE4            (13 | (0 << 8))
#define MAP_ROUTE5            (14 | (0 << 8))
#define MAP_ROUTE6            (15 | (0 << 8))
#define MAP_ROUTE7            (16 | (0 << 8))
#define MAP_ROUTE8            (17 | (0 << 8))
#define MAP_ROUTE9            (18 | (0 << 8))
#define MAP_ROUTE10           (19 | (0 << 8))
#define MAP_ROUTE11           (20 | (0 << 8))
#define MAP_ROUTE31           (21 | (0 << 8))

// Map Group 1
#define MAP_ANHEIM_FOREST          (0 | (1 << 8))
#define MAP_ROCKFALL_CAVE_1F       (1 | (1 << 8))
#define MAP_ROCKFALL_CAVE_B1F      (2 | (1 << 8))
#define MAP_STEEP_RAVINE           (3 | (1 << 8))
#define MAP_TAMAROK_TUNNELS        (4 | (1 << 8))
#define MAP_TAMAROK_PEAK           (5 | (1 << 8))
#define MAP_PALACE_OF_ICE_ENTRANCE (6 | (1 << 8))
#define MAP_PALACE_OF_ICE_INSIDE   (7 | (1 << 8))
#define MAP_SNOWDRIFT_FOREST       (8 | (1 << 8))
#define MAP_MUDDY_UNDERPASS        (9 | (1 << 8))
#define MAP_UNDERWATER             (10 | (1 << 8))

// Map Group 2
#define MAP_ARCTIC_BAY (0 | (2 << 8))

// Map Group 3
#define MAP_CHANDRA_VILLAGE_PLAYER_HOUSE_1F (0 | (3 << 8))
#define MAP_CHANDRA_VILLAGE_PLAYER_HOUSE_2F (1 | (3 << 8))
#define MAP_CHANDRA_VILLAGE_TYLER_HOUSE_1F  (2 | (3 << 8))
#define MAP_CHANDRA_VILLAGE_TYLER_HOUSE_2F  (3 | (3 << 8))
#define MAP_CHANDRA_VILLAGE_LAB             (4 | (3 << 8))

// Map Group 4
#define MAP_SUNRISE_TOWN_HOUSE1            (0 | (4 << 8))
#define MAP_SUNRISE_TOWN_HOUSE2            (1 | (4 << 8))
#define MAP_SUNRISE_TOWN_HOTEL_1F          (2 | (4 << 8))
#define MAP_SUNRISE_TOWN_POKEMON_CENTER_1F (3 | (4 << 8))
#define MAP_SUNRISE_TOWN_MART              (4 | (4 << 8))

// Map Group 5
#define MAP_UNION_CITY_HOUSE1_1F                 (0 | (5 << 8))
#define MAP_UNION_CITY_HOUSE1_2F                 (1 | (5 << 8))
#define MAP_UNION_CITY_HOUSE1_3F                 (2 | (5 << 8))
#define MAP_UNION_CITY_HOUSE2                    (3 | (5 << 8))
#define MAP_UNION_CITY_HOUSE3_1F                 (4 | (5 << 8))
#define MAP_UNION_CITY_HOUSE3_2F                 (5 | (5 << 8))
#define MAP_UNION_CITY_GOV_OFFICE_1F             (6 | (5 << 8))
#define MAP_UNION_CITY_GOV_OFFICE_2F             (7 | (5 << 8))
#define MAP_UNION_CITY_GOV_OFFICE_3F             (8 | (5 << 8))
#define MAP_UNION_CITY_ABANDONED_MUSEUM          (9 | (5 << 8))
#define MAP_UNION_CITY_BIKE_SHOP                 (10 | (5 << 8))
#define MAP_UNION_CITY_GAME_CORNER               (11 | (5 << 8))
#define MAP_UNION_CITY_POKEMON_CENTER_1F         (12 | (5 << 8))
#define MAP_UNION_CITY_DEPARTMENT_STORE_1F       (13 | (5 << 8))
#define MAP_UNION_CITY_DEPARTMENT_STORE_2F       (14 | (5 << 8))
#define MAP_UNION_CITY_DEPARTMENT_STORE_3F       (15 | (5 << 8))
#define MAP_UNION_CITY_DEPARTMENT_STORE_4F       (16 | (5 << 8))
#define MAP_UNION_CITY_DEPARTMENT_STORE_5F       (17 | (5 << 8))
#define MAP_UNION_CITY_DEPARTMENT_STORE_ELEVATOR (18 | (5 << 8))

// Map Group 6
#define MAP_GREENDALE_VILLAGE_HOUSE1            (0 | (6 << 8))
#define MAP_GREENDALE_VILLAGE_ROSE_HOUSE        (1 | (6 << 8))
#define MAP_GREENDALE_VILLAGE_TRAINER_SCHOOL    (2 | (6 << 8))
#define MAP_GREENDALE_VILLAGE_POKEMON_CENTER_1F (3 | (6 << 8))
#define MAP_GREENDALE_VILLAGE_MART              (4 | (6 << 8))

// Map Group 7
#define MAP_ANHEIM_TOWN_HOUSE1            (0 | (7 << 8))
#define MAP_ANHEIM_TOWN_HOUSE2            (1 | (7 << 8))
#define MAP_ANHEIM_TOWN_POKEMON_CENTER_1F (2 | (7 << 8))
#define MAP_ANHEIM_TOWN_MART              (3 | (7 << 8))

// Map Group 8
#define MAP_LAVERIA_CITY_HOUSE1            (0 | (8 << 8))
#define MAP_LAVERIA_CITY_HOUSE2            (1 | (8 << 8))
#define MAP_LAVERIA_CITY_POKEMON_CENTER_1F (2 | (8 << 8))
#define MAP_LAVERIA_CITY_MART              (3 | (8 << 8))

// Map Group 9
#define MAP_HIGHWIND_VILLAGE_HOUSE1            (0 | (9 << 8))
#define MAP_HIGHWIND_VILLAGE_HOUSE2            (1 | (9 << 8))
#define MAP_HIGHWIND_VILLAGE_RANGERS_LODGE     (2 | (9 << 8))
#define MAP_HIGHWIND_VILLAGE_POKEMON_CENTER_1F (3 | (9 << 8))
#define MAP_HIGHWIND_VILLAGE_MART              (4 | (9 << 8))

// Map Group 10
#define MAP_NORTHSTAR_CITY_HOUSE1            (0 | (10 << 8))
#define MAP_NORTHSTAR_CITY_HOUSE2            (1 | (10 << 8))
#define MAP_NORTHSTAR_CITY_HOUSE3            (2 | (10 << 8))
#define MAP_NORTHSTAR_CITY_APARTMENTS        (3 | (10 << 8))
#define MAP_NORTHSTAR_CITY_TRAINER_SCHOOL    (4 | (10 << 8))
#define MAP_NORTHSTAR_CITY_STORAGE_FACILITY  (5 | (10 << 8))
#define MAP_NORTHSTAR_CITY_SHIPPING_CENTER   (6 | (10 << 8))
#define MAP_NORTHSTAR_CITY_TOURNAMENT_1F     (7 | (10 << 8))
#define MAP_NORTHSTAR_CITY_TOURNAMENT_2F     (8 | (10 << 8))
#define MAP_NORTHSTAR_CITY_TOURNAMENT_3F     (9 | (10 << 8))
#define MAP_NORTHSTAR_CITY_TOURNAMENT_4F     (10 | (10 << 8))
#define MAP_NORTHSTAR_CITY_LIGHTHOUSE        (11 | (10 << 8))
#define MAP_NORTHSTAR_CITY_TELESCOPE_SEA     (12 | (10 << 8))
#define MAP_NORTHSTAR_CITY_POKEMON_CENTER_1F (13 | (10 << 8))
#define MAP_NORTHSTAR_CITY_MART              (14 | (10 << 8))

// Map Group 11
#define MAP_PINLEAF_TOWN_HOUSE1           (0 | (11 << 8))
#define MAP_PINLEAF_TOWN_HOUSE2           (1 | (11 << 8))
#define MAP_PINLEAF_TOWN_HOUSE3           (2 | (11 << 8))
#define MAP_PINLEAF_TOWN_HOUSE4           (3 | (11 << 8))
#define MAP_PINLEAF_TOWN_HOUSE5           (4 | (11 << 8))
#define MAP_PINLEAF_TOWN_FARM_HOUSE       (5 | (11 << 8))
#define MAP_PINLEAF_TOWN_STORAGE_FACILITY (6 | (11 << 8))
#define MAP_PINLEAF_TOWN_FLOWER_SHOP      (7 | (11 << 8))
#define MAP_PINLEAF_TOWN_INN_1F           (8 | (11 << 8))
#define MAP_PINLEAF_TOWN_INN_2F           (9 | (11 << 8))
#define MAP_PINLEAF_TOWN_MART             (10 | (11 << 8))

// Map Group 12
#define MAP_ROUTE3_HOUSE1 (0 | (12 << 8))

// Map Group 13
#define MAP_ROUTE4_POKEMON_DAY_CARE (0 | (13 << 8))

// Map Group 14
#define MAP_ROUTE5_HOUSE1 (0 | (14 << 8))

// Map Group 15
#define MAP_ROUTE9_STARTER_DOME (0 | (15 << 8))

// Map Group 16
#define MAP_ANHEIM_FOREST_HOUSE1 (0 | (16 << 8))

// Map Group 17
#define MAP_LAVERIA_CITY_INTERLINK   (0 | (17 << 8))
#define MAP_UNION_CITY_INTERLINK     (1 | (17 << 8))
#define MAP_NORTHSTAR_CITY_INTERLINK (2 | (17 << 8))

// Map Group 18
#define MAP_PETALBURG_CITY      (0 | (18 << 8))
#define MAP_SLATEPORT_CITY      (1 | (18 << 8))
#define MAP_MAUVILLE_CITY       (2 | (18 << 8))
#define MAP_RUSTBORO_CITY       (3 | (18 << 8))
#define MAP_FORTREE_CITY        (4 | (18 << 8))
#define MAP_LILYCOVE_CITY       (5 | (18 << 8))
#define MAP_MOSSDEEP_CITY       (6 | (18 << 8))
#define MAP_SOOTOPOLIS_CITY     (7 | (18 << 8))
#define MAP_EVER_GRANDE_CITY    (8 | (18 << 8))
#define MAP_LITTLEROOT_TOWN     (9 | (18 << 8))
#define MAP_OLDALE_TOWN         (10 | (18 << 8))
#define MAP_DEWFORD_TOWN        (11 | (18 << 8))
#define MAP_LAVARIDGE_TOWN      (12 | (18 << 8))
#define MAP_FALLARBOR_TOWN      (13 | (18 << 8))
#define MAP_VERDANTURF_TOWN     (14 | (18 << 8))
#define MAP_PACIFIDLOG_TOWN     (15 | (18 << 8))
#define MAP_ROUTE101            (16 | (18 << 8))
#define MAP_ROUTE102            (17 | (18 << 8))
#define MAP_ROUTE103            (18 | (18 << 8))
#define MAP_ROUTE104            (19 | (18 << 8))
#define MAP_ROUTE105            (20 | (18 << 8))
#define MAP_ROUTE106            (21 | (18 << 8))
#define MAP_ROUTE107            (22 | (18 << 8))
#define MAP_ROUTE108            (23 | (18 << 8))
#define MAP_ROUTE109            (24 | (18 << 8))
#define MAP_ROUTE110            (25 | (18 << 8))
#define MAP_ROUTE111            (26 | (18 << 8))
#define MAP_ROUTE112            (27 | (18 << 8))
#define MAP_ROUTE113            (28 | (18 << 8))
#define MAP_ROUTE114            (29 | (18 << 8))
#define MAP_ROUTE115            (30 | (18 << 8))
#define MAP_ROUTE116            (31 | (18 << 8))
#define MAP_ROUTE117            (32 | (18 << 8))
#define MAP_ROUTE118            (33 | (18 << 8))
#define MAP_ROUTE119            (34 | (18 << 8))
#define MAP_ROUTE120            (35 | (18 << 8))
#define MAP_ROUTE121            (36 | (18 << 8))
#define MAP_ROUTE122            (37 | (18 << 8))
#define MAP_ROUTE123            (38 | (18 << 8))
#define MAP_ROUTE124            (39 | (18 << 8))
#define MAP_ROUTE125            (40 | (18 << 8))
#define MAP_ROUTE126            (41 | (18 << 8))
#define MAP_ROUTE127            (42 | (18 << 8))
#define MAP_ROUTE128            (43 | (18 << 8))
#define MAP_ROUTE129            (44 | (18 << 8))
#define MAP_ROUTE130            (45 | (18 << 8))
#define MAP_ROUTE131            (46 | (18 << 8))
#define MAP_ROUTE132            (47 | (18 << 8))
#define MAP_ROUTE133            (48 | (18 << 8))
#define MAP_ROUTE134            (49 | (18 << 8))
#define MAP_UNDERWATER_ROUTE124 (50 | (18 << 8))
#define MAP_UNDERWATER_ROUTE126 (51 | (18 << 8))
#define MAP_UNDERWATER_ROUTE127 (52 | (18 << 8))
#define MAP_UNDERWATER_ROUTE128 (53 | (18 << 8))
#define MAP_UNDERWATER_ROUTE129 (54 | (18 << 8))
#define MAP_UNDERWATER_ROUTE105 (55 | (18 << 8))
#define MAP_UNDERWATER_ROUTE125 (56 | (18 << 8))

// Map Group 19
#define MAP_LITTLEROOT_TOWN_BRENDANS_HOUSE_1F    (0 | (19 << 8))
#define MAP_LITTLEROOT_TOWN_BRENDANS_HOUSE_2F    (1 | (19 << 8))
#define MAP_LITTLEROOT_TOWN_MAYS_HOUSE_1F        (2 | (19 << 8))
#define MAP_LITTLEROOT_TOWN_MAYS_HOUSE_2F        (3 | (19 << 8))
#define MAP_LITTLEROOT_TOWN_PROFESSOR_BIRCHS_LAB (4 | (19 << 8))

// Map Group 20
#define MAP_OLDALE_TOWN_HOUSE1            (0 | (20 << 8))
#define MAP_OLDALE_TOWN_HOUSE2            (1 | (20 << 8))
#define MAP_OLDALE_TOWN_POKEMON_CENTER_1F (2 | (20 << 8))
#define MAP_OLDALE_TOWN_POKEMON_CENTER_2F (3 | (20 << 8))
#define MAP_OLDALE_TOWN_MART              (4 | (20 << 8))

// Map Group 21
#define MAP_DEWFORD_TOWN_HOUSE1            (0 | (21 << 8))
#define MAP_DEWFORD_TOWN_POKEMON_CENTER_1F (1 | (21 << 8))
#define MAP_DEWFORD_TOWN_POKEMON_CENTER_2F (2 | (21 << 8))
#define MAP_DEWFORD_TOWN_GYM               (3 | (21 << 8))
#define MAP_DEWFORD_TOWN_HALL              (4 | (21 << 8))
#define MAP_DEWFORD_TOWN_HOUSE2            (5 | (21 << 8))

// Map Group 22
#define MAP_LAVARIDGE_TOWN_HERB_SHOP         (0 | (22 << 8))
#define MAP_LAVARIDGE_TOWN_GYM_1F            (1 | (22 << 8))
#define MAP_LAVARIDGE_TOWN_GYM_B1F           (2 | (22 << 8))
#define MAP_LAVARIDGE_TOWN_HOUSE             (3 | (22 << 8))
#define MAP_LAVARIDGE_TOWN_MART              (4 | (22 << 8))
#define MAP_LAVARIDGE_TOWN_POKEMON_CENTER_1F (5 | (22 << 8))
#define MAP_LAVARIDGE_TOWN_POKEMON_CENTER_2F (6 | (22 << 8))

// Map Group 23
#define MAP_FALLARBOR_TOWN_MART                    (0 | (23 << 8))
#define MAP_FALLARBOR_TOWN_BATTLE_TENT_LOBBY       (1 | (23 << 8))
#define MAP_FALLARBOR_TOWN_BATTLE_TENT_CORRIDOR    (2 | (23 << 8))
#define MAP_FALLARBOR_TOWN_BATTLE_TENT_BATTLE_ROOM (3 | (23 << 8))
#define MAP_FALLARBOR_TOWN_POKEMON_CENTER_1F       (4 | (23 << 8))
#define MAP_FALLARBOR_TOWN_POKEMON_CENTER_2F       (5 | (23 << 8))
#define MAP_FALLARBOR_TOWN_COZMOS_HOUSE            (6 | (23 << 8))
#define MAP_FALLARBOR_TOWN_MOVE_RELEARNERS_HOUSE   (7 | (23 << 8))

// Map Group 24
#define MAP_VERDANTURF_TOWN_BATTLE_TENT_LOBBY       (0 | (24 << 8))
#define MAP_VERDANTURF_TOWN_BATTLE_TENT_CORRIDOR    (1 | (24 << 8))
#define MAP_VERDANTURF_TOWN_BATTLE_TENT_BATTLE_ROOM (2 | (24 << 8))
#define MAP_VERDANTURF_TOWN_MART                    (3 | (24 << 8))
#define MAP_VERDANTURF_TOWN_POKEMON_CENTER_1F       (4 | (24 << 8))
#define MAP_VERDANTURF_TOWN_POKEMON_CENTER_2F       (5 | (24 << 8))
#define MAP_VERDANTURF_TOWN_WANDAS_HOUSE            (6 | (24 << 8))
#define MAP_VERDANTURF_TOWN_FRIENDSHIP_RATERS_HOUSE (7 | (24 << 8))
#define MAP_VERDANTURF_TOWN_HOUSE                   (8 | (24 << 8))

// Map Group 25
#define MAP_PACIFIDLOG_TOWN_POKEMON_CENTER_1F (0 | (25 << 8))
#define MAP_PACIFIDLOG_TOWN_POKEMON_CENTER_2F (1 | (25 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE1            (2 | (25 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE2            (3 | (25 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE3            (4 | (25 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE4            (5 | (25 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE5            (6 | (25 << 8))

// Map Group 26
#define MAP_PETALBURG_CITY_WALLYS_HOUSE      (0 | (26 << 8))
#define MAP_PETALBURG_CITY_GYM               (1 | (26 << 8))
#define MAP_PETALBURG_CITY_HOUSE1            (2 | (26 << 8))
#define MAP_PETALBURG_CITY_HOUSE2            (3 | (26 << 8))
#define MAP_PETALBURG_CITY_POKEMON_CENTER_1F (4 | (26 << 8))
#define MAP_PETALBURG_CITY_POKEMON_CENTER_2F (5 | (26 << 8))
#define MAP_PETALBURG_CITY_MART              (6 | (26 << 8))

// Map Group 27
#define MAP_SLATEPORT_CITY_STERNS_SHIPYARD_1F      (0 | (27 << 8))
#define MAP_SLATEPORT_CITY_STERNS_SHIPYARD_2F      (1 | (27 << 8))
#define MAP_SLATEPORT_CITY_BATTLE_TENT_LOBBY       (2 | (27 << 8))
#define MAP_SLATEPORT_CITY_BATTLE_TENT_CORRIDOR    (3 | (27 << 8))
#define MAP_SLATEPORT_CITY_BATTLE_TENT_BATTLE_ROOM (4 | (27 << 8))
#define MAP_SLATEPORT_CITY_NAME_RATERS_HOUSE       (5 | (27 << 8))
#define MAP_SLATEPORT_CITY_POKEMON_FAN_CLUB        (6 | (27 << 8))
#define MAP_SLATEPORT_CITY_OCEANIC_MUSEUM_1F       (7 | (27 << 8))
#define MAP_SLATEPORT_CITY_OCEANIC_MUSEUM_2F       (8 | (27 << 8))
#define MAP_SLATEPORT_CITY_HARBOR                  (9 | (27 << 8))
#define MAP_SLATEPORT_CITY_HOUSE                   (10 | (27 << 8))
#define MAP_SLATEPORT_CITY_POKEMON_CENTER_1F       (11 | (27 << 8))
#define MAP_SLATEPORT_CITY_POKEMON_CENTER_2F       (12 | (27 << 8))
#define MAP_SLATEPORT_CITY_MART                    (13 | (27 << 8))

// Map Group 28
#define MAP_MAUVILLE_CITY_GYM               (0 | (28 << 8))
#define MAP_MAUVILLE_CITY_BIKE_SHOP         (1 | (28 << 8))
#define MAP_MAUVILLE_CITY_HOUSE1            (2 | (28 << 8))
#define MAP_MAUVILLE_CITY_GAME_CORNER       (3 | (28 << 8))
#define MAP_MAUVILLE_CITY_HOUSE2            (4 | (28 << 8))
#define MAP_MAUVILLE_CITY_POKEMON_CENTER_1F (5 | (28 << 8))
#define MAP_MAUVILLE_CITY_POKEMON_CENTER_2F (6 | (28 << 8))
#define MAP_MAUVILLE_CITY_MART              (7 | (28 << 8))

// Map Group 29
#define MAP_RUSTBORO_CITY_DEVON_CORP_1F     (0 | (29 << 8))
#define MAP_RUSTBORO_CITY_DEVON_CORP_2F     (1 | (29 << 8))
#define MAP_RUSTBORO_CITY_DEVON_CORP_3F     (2 | (29 << 8))
#define MAP_RUSTBORO_CITY_GYM               (3 | (29 << 8))
#define MAP_RUSTBORO_CITY_POKEMON_SCHOOL    (4 | (29 << 8))
#define MAP_RUSTBORO_CITY_POKEMON_CENTER_1F (5 | (29 << 8))
#define MAP_RUSTBORO_CITY_POKEMON_CENTER_2F (6 | (29 << 8))
#define MAP_RUSTBORO_CITY_MART              (7 | (29 << 8))
#define MAP_RUSTBORO_CITY_FLAT1_1F          (8 | (29 << 8))
#define MAP_RUSTBORO_CITY_FLAT1_2F          (9 | (29 << 8))
#define MAP_RUSTBORO_CITY_HOUSE1            (10 | (29 << 8))
#define MAP_RUSTBORO_CITY_CUTTERS_HOUSE     (11 | (29 << 8))
#define MAP_RUSTBORO_CITY_HOUSE2            (12 | (29 << 8))
#define MAP_RUSTBORO_CITY_FLAT2_1F          (13 | (29 << 8))
#define MAP_RUSTBORO_CITY_FLAT2_2F          (14 | (29 << 8))
#define MAP_RUSTBORO_CITY_FLAT2_3F          (15 | (29 << 8))
#define MAP_RUSTBORO_CITY_HOUSE3            (16 | (29 << 8))

// Map Group 30
#define MAP_FORTREE_CITY_HOUSE1            (0 | (30 << 8))
#define MAP_FORTREE_CITY_GYM               (1 | (30 << 8))
#define MAP_FORTREE_CITY_POKEMON_CENTER_1F (2 | (30 << 8))
#define MAP_FORTREE_CITY_POKEMON_CENTER_2F (3 | (30 << 8))
#define MAP_FORTREE_CITY_MART              (4 | (30 << 8))
#define MAP_FORTREE_CITY_HOUSE2            (5 | (30 << 8))
#define MAP_FORTREE_CITY_HOUSE3            (6 | (30 << 8))
#define MAP_FORTREE_CITY_HOUSE4            (7 | (30 << 8))
#define MAP_FORTREE_CITY_HOUSE5            (8 | (30 << 8))
#define MAP_FORTREE_CITY_DECORATION_SHOP   (9 | (30 << 8))

// Map Group 31
#define MAP_LILYCOVE_CITY_COVE_LILY_MOTEL_1F        (0 | (31 << 8))
#define MAP_LILYCOVE_CITY_COVE_LILY_MOTEL_2F        (1 | (31 << 8))
#define MAP_LILYCOVE_CITY_LILYCOVE_MUSEUM_1F        (2 | (31 << 8))
#define MAP_LILYCOVE_CITY_LILYCOVE_MUSEUM_2F        (3 | (31 << 8))
#define MAP_LILYCOVE_CITY_CONTEST_LOBBY             (4 | (31 << 8))
#define MAP_LILYCOVE_CITY_CONTEST_HALL              (5 | (31 << 8))
#define MAP_LILYCOVE_CITY_POKEMON_CENTER_1F         (6 | (31 << 8))
#define MAP_LILYCOVE_CITY_POKEMON_CENTER_2F         (7 | (31 << 8))
#define MAP_LILYCOVE_CITY_UNUSED_MART               (8 | (31 << 8))
#define MAP_LILYCOVE_CITY_POKEMON_TRAINER_FAN_CLUB  (9 | (31 << 8))
#define MAP_LILYCOVE_CITY_HARBOR                    (10 | (31 << 8))
#define MAP_LILYCOVE_CITY_MOVE_DELETERS_HOUSE       (11 | (31 << 8))
#define MAP_LILYCOVE_CITY_HOUSE1                    (12 | (31 << 8))
#define MAP_LILYCOVE_CITY_HOUSE2                    (13 | (31 << 8))
#define MAP_LILYCOVE_CITY_HOUSE3                    (14 | (31 << 8))
#define MAP_LILYCOVE_CITY_HOUSE4                    (15 | (31 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_1F       (16 | (31 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_2F       (17 | (31 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_3F       (18 | (31 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_4F       (19 | (31 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_5F       (20 | (31 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_ROOFTOP  (21 | (31 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_ELEVATOR (22 | (31 << 8))

// Map Group 32
#define MAP_MOSSDEEP_CITY_GYM               (0 | (32 << 8))
#define MAP_MOSSDEEP_CITY_HOUSE1            (1 | (32 << 8))
#define MAP_MOSSDEEP_CITY_HOUSE2            (2 | (32 << 8))
#define MAP_MOSSDEEP_CITY_POKEMON_CENTER_1F (3 | (32 << 8))
#define MAP_MOSSDEEP_CITY_POKEMON_CENTER_2F (4 | (32 << 8))
#define MAP_MOSSDEEP_CITY_MART              (5 | (32 << 8))
#define MAP_MOSSDEEP_CITY_HOUSE3            (6 | (32 << 8))
#define MAP_MOSSDEEP_CITY_STEVENS_HOUSE     (7 | (32 << 8))
#define MAP_MOSSDEEP_CITY_HOUSE4            (8 | (32 << 8))
#define MAP_MOSSDEEP_CITY_SPACE_CENTER_1F   (9 | (32 << 8))
#define MAP_MOSSDEEP_CITY_SPACE_CENTER_2F   (10 | (32 << 8))
#define MAP_MOSSDEEP_CITY_GAME_CORNER_1F    (11 | (32 << 8))
#define MAP_MOSSDEEP_CITY_GAME_CORNER_B1F   (12 | (32 << 8))

// Map Group 33
#define MAP_SOOTOPOLIS_CITY_GYM_1F                   (0 | (33 << 8))
#define MAP_SOOTOPOLIS_CITY_GYM_B1F                  (1 | (33 << 8))
#define MAP_SOOTOPOLIS_CITY_POKEMON_CENTER_1F        (2 | (33 << 8))
#define MAP_SOOTOPOLIS_CITY_POKEMON_CENTER_2F        (3 | (33 << 8))
#define MAP_SOOTOPOLIS_CITY_MART                     (4 | (33 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE1                   (5 | (33 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE2                   (6 | (33 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE3                   (7 | (33 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE4                   (8 | (33 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE5                   (9 | (33 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE6                   (10 | (33 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE7                   (11 | (33 << 8))
#define MAP_SOOTOPOLIS_CITY_LOTAD_AND_SEEDOT_HOUSE   (12 | (33 << 8))
#define MAP_SOOTOPOLIS_CITY_MYSTERY_EVENTS_HOUSE_1F  (13 | (33 << 8))
#define MAP_SOOTOPOLIS_CITY_MYSTERY_EVENTS_HOUSE_B1F (14 | (33 << 8))

// Map Group 34
#define MAP_EVER_GRANDE_CITY_SIDNEYS_ROOM      (0 | (34 << 8))
#define MAP_EVER_GRANDE_CITY_PHOEBES_ROOM      (1 | (34 << 8))
#define MAP_EVER_GRANDE_CITY_GLACIAS_ROOM      (2 | (34 << 8))
#define MAP_EVER_GRANDE_CITY_DRAKES_ROOM       (3 | (34 << 8))
#define MAP_EVER_GRANDE_CITY_CHAMPIONS_ROOM    (4 | (34 << 8))
#define MAP_EVER_GRANDE_CITY_HALL1             (5 | (34 << 8))
#define MAP_EVER_GRANDE_CITY_HALL2             (6 | (34 << 8))
#define MAP_EVER_GRANDE_CITY_HALL3             (7 | (34 << 8))
#define MAP_EVER_GRANDE_CITY_HALL4             (8 | (34 << 8))
#define MAP_EVER_GRANDE_CITY_HALL5             (9 | (34 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_LEAGUE_1F (10 | (34 << 8))
#define MAP_EVER_GRANDE_CITY_HALL_OF_FAME      (11 | (34 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_CENTER_1F (12 | (34 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_CENTER_2F (13 | (34 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_LEAGUE_2F (14 | (34 << 8))

// Map Group 35
#define MAP_ROUTE104_MR_BRINEYS_HOUSE         (0 | (35 << 8))
#define MAP_ROUTE104_PRETTY_PETAL_FLOWER_SHOP (1 | (35 << 8))

// Map Group 36
#define MAP_ROUTE111_WINSTRATE_FAMILYS_HOUSE (0 | (36 << 8))
#define MAP_ROUTE111_OLD_LADYS_REST_STOP     (1 | (36 << 8))

// Map Group 37
#define MAP_ROUTE112_CABLE_CAR_STATION   (0 | (37 << 8))
#define MAP_MT_CHIMNEY_CABLE_CAR_STATION (1 | (37 << 8))

// Map Group 38
#define MAP_ROUTE114_FOSSIL_MANIACS_HOUSE  (0 | (38 << 8))
#define MAP_ROUTE114_FOSSIL_MANIACS_TUNNEL (1 | (38 << 8))
#define MAP_ROUTE114_LANETTES_HOUSE        (2 | (38 << 8))

// Map Group 39
#define MAP_ROUTE116_TUNNELERS_REST_HOUSE (0 | (39 << 8))

// Map Group 40
#define MAP_ROUTE117_POKEMON_DAY_CARE (0 | (40 << 8))

// Map Group 41
#define MAP_ROUTE121_SAFARI_ZONE_ENTRANCE (0 | (41 << 8))

// Map Group 42
#define MAP_METEOR_FALLS_1F_1R                       (0 | (42 << 8))
#define MAP_METEOR_FALLS_1F_2R                       (1 | (42 << 8))
#define MAP_METEOR_FALLS_B1F_1R                      (2 | (42 << 8))
#define MAP_METEOR_FALLS_B1F_2R                      (3 | (42 << 8))
#define MAP_RUSTURF_TUNNEL                           (4 | (42 << 8))
#define MAP_UNDERWATER_SOOTOPOLIS_CITY               (5 | (42 << 8))
#define MAP_DESERT_RUINS                             (6 | (42 << 8))
#define MAP_GRANITE_CAVE_1F                          (7 | (42 << 8))
#define MAP_GRANITE_CAVE_B1F                         (8 | (42 << 8))
#define MAP_GRANITE_CAVE_B2F                         (9 | (42 << 8))
#define MAP_GRANITE_CAVE_STEVENS_ROOM                (10 | (42 << 8))
#define MAP_PETALBURG_WOODS                          (11 | (42 << 8))
#define MAP_MT_CHIMNEY                               (12 | (42 << 8))
#define MAP_JAGGED_PASS                              (13 | (42 << 8))
#define MAP_FIERY_PATH                               (14 | (42 << 8))
#define MAP_MT_PYRE_1F                               (15 | (42 << 8))
#define MAP_MT_PYRE_2F                               (16 | (42 << 8))
#define MAP_MT_PYRE_3F                               (17 | (42 << 8))
#define MAP_MT_PYRE_4F                               (18 | (42 << 8))
#define MAP_MT_PYRE_5F                               (19 | (42 << 8))
#define MAP_MT_PYRE_6F                               (20 | (42 << 8))
#define MAP_MT_PYRE_EXTERIOR                         (21 | (42 << 8))
#define MAP_MT_PYRE_SUMMIT                           (22 | (42 << 8))
#define MAP_AQUA_HIDEOUT_1F                          (23 | (42 << 8))
#define MAP_AQUA_HIDEOUT_B1F                         (24 | (42 << 8))
#define MAP_AQUA_HIDEOUT_B2F                         (25 | (42 << 8))
#define MAP_UNDERWATER_SEAFLOOR_CAVERN               (26 | (42 << 8))
#define MAP_SEAFLOOR_CAVERN_ENTRANCE                 (27 | (42 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM1                    (28 | (42 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM2                    (29 | (42 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM3                    (30 | (42 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM4                    (31 | (42 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM5                    (32 | (42 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM6                    (33 | (42 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM7                    (34 | (42 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM8                    (35 | (42 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM9                    (36 | (42 << 8))
#define MAP_CAVE_OF_ORIGIN_ENTRANCE                  (37 | (42 << 8))
#define MAP_CAVE_OF_ORIGIN_1F                        (38 | (42 << 8))
#define MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP1 (39 | (42 << 8))
#define MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP2 (40 | (42 << 8))
#define MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP3 (41 | (42 << 8))
#define MAP_CAVE_OF_ORIGIN_B1F                       (42 | (42 << 8))
#define MAP_VICTORY_ROAD_1F                          (43 | (42 << 8))
#define MAP_VICTORY_ROAD_B1F                         (44 | (42 << 8))
#define MAP_VICTORY_ROAD_B2F                         (45 | (42 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_ENTRANCE_ROOM        (46 | (42 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_INNER_ROOM           (47 | (42 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_STAIRS_ROOM          (48 | (42 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_LOWER_ROOM           (49 | (42 << 8))
#define MAP_SHOAL_CAVE_HIGH_TIDE_ENTRANCE_ROOM       (50 | (42 << 8))
#define MAP_SHOAL_CAVE_HIGH_TIDE_INNER_ROOM          (51 | (42 << 8))
#define MAP_NEW_MAUVILLE_ENTRANCE                    (52 | (42 << 8))
#define MAP_NEW_MAUVILLE_INSIDE                      (53 | (42 << 8))
#define MAP_ABANDONED_SHIP_DECK                      (54 | (42 << 8))
#define MAP_ABANDONED_SHIP_CORRIDORS_1F              (55 | (42 << 8))
#define MAP_ABANDONED_SHIP_ROOMS_1F                  (56 | (42 << 8))
#define MAP_ABANDONED_SHIP_CORRIDORS_B1F             (57 | (42 << 8))
#define MAP_ABANDONED_SHIP_ROOMS_B1F                 (58 | (42 << 8))
#define MAP_ABANDONED_SHIP_ROOMS2_B1F                (59 | (42 << 8))
#define MAP_ABANDONED_SHIP_UNDERWATER1               (60 | (42 << 8))
#define MAP_ABANDONED_SHIP_ROOM_B1F                  (61 | (42 << 8))
#define MAP_ABANDONED_SHIP_ROOMS2_1F                 (62 | (42 << 8))
#define MAP_ABANDONED_SHIP_CAPTAINS_OFFICE           (63 | (42 << 8))
#define MAP_ABANDONED_SHIP_UNDERWATER2               (64 | (42 << 8))
#define MAP_ABANDONED_SHIP_HIDDEN_FLOOR_CORRIDORS    (65 | (42 << 8))
#define MAP_ABANDONED_SHIP_HIDDEN_FLOOR_ROOMS        (66 | (42 << 8))
#define MAP_ISLAND_CAVE                              (67 | (42 << 8))
#define MAP_ANCIENT_TOMB                             (68 | (42 << 8))
#define MAP_UNDERWATER_ROUTE134                      (69 | (42 << 8))
#define MAP_UNDERWATER_SEALED_CHAMBER                (70 | (42 << 8))
#define MAP_SEALED_CHAMBER_OUTER_ROOM                (71 | (42 << 8))
#define MAP_SEALED_CHAMBER_INNER_ROOM                (72 | (42 << 8))
#define MAP_SCORCHED_SLAB                            (73 | (42 << 8))
#define MAP_AQUA_HIDEOUT_UNUSED_RUBY_MAP1            (74 | (42 << 8))
#define MAP_AQUA_HIDEOUT_UNUSED_RUBY_MAP2            (75 | (42 << 8))
#define MAP_AQUA_HIDEOUT_UNUSED_RUBY_MAP3            (76 | (42 << 8))
#define MAP_SKY_PILLAR_ENTRANCE                      (77 | (42 << 8))
#define MAP_SKY_PILLAR_OUTSIDE                       (78 | (42 << 8))
#define MAP_SKY_PILLAR_1F                            (79 | (42 << 8))
#define MAP_SKY_PILLAR_2F                            (80 | (42 << 8))
#define MAP_SKY_PILLAR_3F                            (81 | (42 << 8))
#define MAP_SKY_PILLAR_4F                            (82 | (42 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_ICE_ROOM             (83 | (42 << 8))
#define MAP_SKY_PILLAR_5F                            (84 | (42 << 8))
#define MAP_SKY_PILLAR_TOP                           (85 | (42 << 8))
#define MAP_MAGMA_HIDEOUT_1F                         (86 | (42 << 8))
#define MAP_MAGMA_HIDEOUT_2F_1R                      (87 | (42 << 8))
#define MAP_MAGMA_HIDEOUT_2F_2R                      (88 | (42 << 8))
#define MAP_MAGMA_HIDEOUT_3F_1R                      (89 | (42 << 8))
#define MAP_MAGMA_HIDEOUT_3F_2R                      (90 | (42 << 8))
#define MAP_MAGMA_HIDEOUT_4F                         (91 | (42 << 8))
#define MAP_MAGMA_HIDEOUT_3F_3R                      (92 | (42 << 8))
#define MAP_MAGMA_HIDEOUT_2F_3R                      (93 | (42 << 8))
#define MAP_MIRAGE_TOWER_1F                          (94 | (42 << 8))
#define MAP_MIRAGE_TOWER_2F                          (95 | (42 << 8))
#define MAP_MIRAGE_TOWER_3F                          (96 | (42 << 8))
#define MAP_MIRAGE_TOWER_4F                          (97 | (42 << 8))
#define MAP_DESERT_UNDERPASS                         (98 | (42 << 8))
#define MAP_ARTISAN_CAVE_B1F                         (99 | (42 << 8))
#define MAP_ARTISAN_CAVE_1F                          (100 | (42 << 8))
#define MAP_UNDERWATER_MARINE_CAVE                   (101 | (42 << 8))
#define MAP_MARINE_CAVE_ENTRANCE                     (102 | (42 << 8))
#define MAP_MARINE_CAVE_END                          (103 | (42 << 8))
#define MAP_TERRA_CAVE_ENTRANCE                      (104 | (42 << 8))
#define MAP_TERRA_CAVE_END                           (105 | (42 << 8))
#define MAP_ALTERING_CAVE                            (106 | (42 << 8))
#define MAP_METEOR_FALLS_STEVENS_CAVE                (107 | (42 << 8))

// Map Group 43
#define MAP_SECRET_BASE_RED_CAVE1    (0 | (43 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE1  (1 | (43 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE1   (2 | (43 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE1 (3 | (43 << 8))
#define MAP_SECRET_BASE_TREE1        (4 | (43 << 8))
#define MAP_SECRET_BASE_SHRUB1       (5 | (43 << 8))
#define MAP_SECRET_BASE_RED_CAVE2    (6 | (43 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE2  (7 | (43 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE2   (8 | (43 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE2 (9 | (43 << 8))
#define MAP_SECRET_BASE_TREE2        (10 | (43 << 8))
#define MAP_SECRET_BASE_SHRUB2       (11 | (43 << 8))
#define MAP_SECRET_BASE_RED_CAVE3    (12 | (43 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE3  (13 | (43 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE3   (14 | (43 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE3 (15 | (43 << 8))
#define MAP_SECRET_BASE_TREE3        (16 | (43 << 8))
#define MAP_SECRET_BASE_SHRUB3       (17 | (43 << 8))
#define MAP_SECRET_BASE_RED_CAVE4    (18 | (43 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE4  (19 | (43 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE4   (20 | (43 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE4 (21 | (43 << 8))
#define MAP_SECRET_BASE_TREE4        (22 | (43 << 8))
#define MAP_SECRET_BASE_SHRUB4       (23 | (43 << 8))
#define MAP_BATTLE_COLOSSEUM_2P      (24 | (43 << 8))
#define MAP_TRADE_CENTER             (25 | (43 << 8))
#define MAP_RECORD_CORNER            (26 | (43 << 8))
#define MAP_BATTLE_COLOSSEUM_4P      (27 | (43 << 8))
#define MAP_CONTEST_HALL             (28 | (43 << 8))
#define MAP_UNUSED_CONTEST_HALL1     (29 | (43 << 8))
#define MAP_UNUSED_CONTEST_HALL2     (30 | (43 << 8))
#define MAP_UNUSED_CONTEST_HALL3     (31 | (43 << 8))
#define MAP_UNUSED_CONTEST_HALL4     (32 | (43 << 8))
#define MAP_UNUSED_CONTEST_HALL5     (33 | (43 << 8))
#define MAP_UNUSED_CONTEST_HALL6     (34 | (43 << 8))
#define MAP_CONTEST_HALL_BEAUTY      (35 | (43 << 8))
#define MAP_CONTEST_HALL_TOUGH       (36 | (43 << 8))
#define MAP_CONTEST_HALL_COOL        (37 | (43 << 8))
#define MAP_CONTEST_HALL_SMART       (38 | (43 << 8))
#define MAP_CONTEST_HALL_CUTE        (39 | (43 << 8))
#define MAP_INSIDE_OF_TRUCK          (40 | (43 << 8))
#define MAP_SS_TIDAL_CORRIDOR        (41 | (43 << 8))
#define MAP_SS_TIDAL_LOWER_DECK      (42 | (43 << 8))
#define MAP_SS_TIDAL_ROOMS           (43 | (43 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE01  (44 | (43 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE02  (45 | (43 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE03  (46 | (43 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE04  (47 | (43 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE05  (48 | (43 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE06  (49 | (43 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE07  (50 | (43 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE08  (51 | (43 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE09  (52 | (43 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE10  (53 | (43 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE11  (54 | (43 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE12  (55 | (43 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE13  (56 | (43 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE14  (57 | (43 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE15  (58 | (43 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE16  (59 | (43 << 8))
#define MAP_UNION_ROOM               (60 | (43 << 8))

// Map Group 44
#define MAP_SAFARI_ZONE_NORTHWEST                           (0 | (44 << 8))
#define MAP_SAFARI_ZONE_NORTH                               (1 | (44 << 8))
#define MAP_SAFARI_ZONE_SOUTHWEST                           (2 | (44 << 8))
#define MAP_SAFARI_ZONE_SOUTH                               (3 | (44 << 8))
#define MAP_BATTLE_FRONTIER_OUTSIDE_WEST                    (4 | (44 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_LOBBY              (5 | (44 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_ELEVATOR           (6 | (44 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_CORRIDOR           (7 | (44 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_BATTLE_ROOM        (8 | (44 << 8))
#define MAP_SOUTHERN_ISLAND_EXTERIOR                        (9 | (44 << 8))
#define MAP_SOUTHERN_ISLAND_INTERIOR                        (10 | (44 << 8))
#define MAP_SAFARI_ZONE_REST_HOUSE                          (11 | (44 << 8))
#define MAP_SAFARI_ZONE_NORTHEAST                           (12 | (44 << 8))
#define MAP_SAFARI_ZONE_SOUTHEAST                           (13 | (44 << 8))
#define MAP_BATTLE_FRONTIER_OUTSIDE_EAST                    (14 | (44 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_PARTNER_ROOM (15 | (44 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_CORRIDOR     (16 | (44 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_BATTLE_ROOM  (17 | (44 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_LOBBY               (18 | (44 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_CORRIDOR            (19 | (44 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_PRE_BATTLE_ROOM     (20 | (44 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_BATTLE_ROOM         (21 | (44 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_LOBBY             (22 | (44 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_CORRIDOR          (23 | (44 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_BATTLE_ROOM       (24 | (44 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_LOBBY            (25 | (44 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_FLOOR            (26 | (44 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_TOP              (27 | (44 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_LOBBY              (28 | (44 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_CORRIDOR           (29 | (44 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_BATTLE_ROOM        (30 | (44 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_LOBBY            (31 | (44 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_PRE_BATTLE_ROOM  (32 | (44 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_BATTLE_ROOM      (33 | (44 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_LOBBY               (34 | (44 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_CORRIDOR            (35 | (44 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_THREE_PATH_ROOM     (36 | (44 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_NORMAL         (37 | (44 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_FINAL          (38 | (44 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_WILD_MONS      (39 | (44 << 8))
#define MAP_BATTLE_FRONTIER_RANKING_HALL                    (40 | (44 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE1                         (41 | (44 << 8))
#define MAP_BATTLE_FRONTIER_EXCHANGE_SERVICE_CORNER         (42 | (44 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE2                         (43 | (44 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE3                         (44 | (44 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE4                         (45 | (44 << 8))
#define MAP_BATTLE_FRONTIER_SCOTTS_HOUSE                    (46 | (44 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE5                         (47 | (44 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE6                         (48 | (44 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE7                         (49 | (44 << 8))
#define MAP_BATTLE_FRONTIER_RECEPTION_GATE                  (50 | (44 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE8                         (51 | (44 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE9                         (52 | (44 << 8))
#define MAP_BATTLE_FRONTIER_POKEMON_CENTER_1F               (53 | (44 << 8))
#define MAP_BATTLE_FRONTIER_POKEMON_CENTER_2F               (54 | (44 << 8))
#define MAP_BATTLE_FRONTIER_MART                            (55 | (44 << 8))
#define MAP_FARAWAY_ISLAND_ENTRANCE                         (56 | (44 << 8))
#define MAP_FARAWAY_ISLAND_INTERIOR                         (57 | (44 << 8))
#define MAP_BIRTH_ISLAND_EXTERIOR                           (58 | (44 << 8))
#define MAP_BIRTH_ISLAND_HARBOR                             (59 | (44 << 8))
#define MAP_TRAINER_HILL_ENTRANCE                           (60 | (44 << 8))
#define MAP_TRAINER_HILL_1F                                 (61 | (44 << 8))
#define MAP_TRAINER_HILL_2F                                 (62 | (44 << 8))
#define MAP_TRAINER_HILL_3F                                 (63 | (44 << 8))
#define MAP_TRAINER_HILL_4F                                 (64 | (44 << 8))
#define MAP_TRAINER_HILL_ROOF                               (65 | (44 << 8))
#define MAP_NAVEL_ROCK_EXTERIOR                             (66 | (44 << 8))
#define MAP_NAVEL_ROCK_HARBOR                               (67 | (44 << 8))
#define MAP_NAVEL_ROCK_ENTRANCE                             (68 | (44 << 8))
#define MAP_NAVEL_ROCK_B1F                                  (69 | (44 << 8))
#define MAP_NAVEL_ROCK_FORK                                 (70 | (44 << 8))
#define MAP_NAVEL_ROCK_UP1                                  (71 | (44 << 8))
#define MAP_NAVEL_ROCK_UP2                                  (72 | (44 << 8))
#define MAP_NAVEL_ROCK_UP3                                  (73 | (44 << 8))
#define MAP_NAVEL_ROCK_UP4                                  (74 | (44 << 8))
#define MAP_NAVEL_ROCK_TOP                                  (75 | (44 << 8))
#define MAP_NAVEL_ROCK_DOWN01                               (76 | (44 << 8))
#define MAP_NAVEL_ROCK_DOWN02                               (77 | (44 << 8))
#define MAP_NAVEL_ROCK_DOWN03                               (78 | (44 << 8))
#define MAP_NAVEL_ROCK_DOWN04                               (79 | (44 << 8))
#define MAP_NAVEL_ROCK_DOWN05                               (80 | (44 << 8))
#define MAP_NAVEL_ROCK_DOWN06                               (81 | (44 << 8))
#define MAP_NAVEL_ROCK_DOWN07                               (82 | (44 << 8))
#define MAP_NAVEL_ROCK_DOWN08                               (83 | (44 << 8))
#define MAP_NAVEL_ROCK_DOWN09                               (84 | (44 << 8))
#define MAP_NAVEL_ROCK_DOWN10                               (85 | (44 << 8))
#define MAP_NAVEL_ROCK_DOWN11                               (86 | (44 << 8))
#define MAP_NAVEL_ROCK_BOTTOM                               (87 | (44 << 8))
#define MAP_TRAINER_HILL_ELEVATOR                           (88 | (44 << 8))

// Map Group 45
#define MAP_ROUTE104_PROTOTYPE                          (0 | (45 << 8))
#define MAP_ROUTE104_PROTOTYPE_PRETTY_PETAL_FLOWER_SHOP (1 | (45 << 8))

// Map Group 46
#define MAP_ROUTE109_SEASHORE_HOUSE (0 | (46 << 8))

// Map Group 47
#define MAP_ROUTE110_TRICK_HOUSE_ENTRANCE                (0 | (47 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_END                     (1 | (47 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_CORRIDOR                (2 | (47 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE1                 (3 | (47 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE2                 (4 | (47 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE3                 (5 | (47 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE4                 (6 | (47 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE5                 (7 | (47 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE6                 (8 | (47 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE7                 (9 | (47 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE8                 (10 | (47 << 8))
#define MAP_ROUTE110_SEASIDE_CYCLING_ROAD_NORTH_ENTRANCE (11 | (47 << 8))
#define MAP_ROUTE110_SEASIDE_CYCLING_ROAD_SOUTH_ENTRANCE (12 | (47 << 8))

// Map Group 48
#define MAP_ROUTE113_GLASS_WORKSHOP (0 | (48 << 8))

// Map Group 49
#define MAP_ROUTE123_BERRY_MASTERS_HOUSE (0 | (49 << 8))

// Map Group 50
#define MAP_ROUTE119_WEATHER_INSTITUTE_1F (0 | (50 << 8))
#define MAP_ROUTE119_WEATHER_INSTITUTE_2F (1 | (50 << 8))
#define MAP_ROUTE119_HOUSE                (2 | (50 << 8))

// Map Group 51
#define MAP_ROUTE124_DIVING_TREASURE_HUNTERS_HOUSE (0 | (51 << 8))

#define MAP_GROUPS_COUNT 52

#endif // GUARD_CONSTANTS_MAP_GROUPS_H
