#ifndef GUARD_CONSTANTS_MAP_GROUPS_H
#define GUARD_CONSTANTS_MAP_GROUPS_H

//
// DO NOT MODIFY THIS FILE! It is auto-generated from data/maps/map_groups.json
//

// gMapGroup_DarkfireMain
#define MAP_CHANDRA_VILLAGE   (0 | (0 << 8))
#define MAP_SUNRISE_TOWN      (1 | (0 << 8))
#define MAP_UNION_CITY        (2 | (0 << 8))
#define MAP_GREENDALE_VILLAGE (3 | (0 << 8))
#define MAP_ANHEIM_TOWN       (4 | (0 << 8))
#define MAP_LAVERIA_CITY      (5 | (0 << 8))
#define MAP_HIGHWIND_VILLAGE  (6 | (0 << 8))
#define MAP_NORTHSTAR_CITY    (7 | (0 << 8))
#define MAP_PINLEAF_TOWN      (8 | (0 << 8))
#define MAP_WATERWAY_CITY     (9 | (0 << 8))
#define MAP_MAYHEM_CITY       (10 | (0 << 8))
#define MAP_MOONSPRING_CITY   (11 | (0 << 8))
#define MAP_ZONYA_VILLAGE     (12 | (0 << 8))
#define MAP_DRIFTSTREAM_TOWN  (13 | (0 << 8))
#define MAP_MIRANIA_TOWN      (14 | (0 << 8))
#define MAP_THYMESGROVE_CITY  (15 | (0 << 8))
#define MAP_TWILIGHT_VILLAGE  (16 | (0 << 8))
#define MAP_PORT_BALINA       (17 | (0 << 8))
#define MAP_WEST_DISTRICT     (18 | (0 << 8))
#define MAP_BATTLE_DISTRICT   (19 | (0 << 8))
#define MAP_PORT              (20 | (0 << 8))
#define MAP_OUTSKIRTS         (21 | (0 << 8))
#define MAP_ROUTE1            (22 | (0 << 8))
#define MAP_ROUTE2            (23 | (0 << 8))
#define MAP_ROUTE3            (24 | (0 << 8))
#define MAP_ROUTE4            (25 | (0 << 8))
#define MAP_ROUTE5            (26 | (0 << 8))
#define MAP_ROUTE6            (27 | (0 << 8))
#define MAP_ROUTE7            (28 | (0 << 8))
#define MAP_ROUTE8            (29 | (0 << 8))
#define MAP_ROUTE9            (30 | (0 << 8))
#define MAP_ROUTE10           (31 | (0 << 8))
#define MAP_ROUTE11           (32 | (0 << 8))
#define MAP_ROUTE12           (33 | (0 << 8))
#define MAP_ROUTE13           (34 | (0 << 8))
#define MAP_ROUTE14           (35 | (0 << 8))
#define MAP_ROUTE15           (36 | (0 << 8))
#define MAP_ROUTE16           (37 | (0 << 8))
#define MAP_ROUTE17           (38 | (0 << 8))
#define MAP_ROUTE22           (39 | (0 << 8))
#define MAP_ROUTE25           (40 | (0 << 8))
#define MAP_ROUTE31           (41 | (0 << 8))

// gMapGroup_DarkfireDungeons
#define MAP_ANHEIM_FOREST          (0 | (1 << 8))
#define MAP_ROCKFALL_CAVE_1F       (1 | (1 << 8))
#define MAP_ROCKFALL_CAVE_B1F      (2 | (1 << 8))
#define MAP_STEEP_RAVINE           (3 | (1 << 8))
#define MAP_TAMAROK_TUNNELS        (4 | (1 << 8))
#define MAP_TAMAROK_PEAK           (5 | (1 << 8))
#define MAP_PALACE_OF_ICE_ENTRANCE (6 | (1 << 8))
#define MAP_PALACE_OF_ICE_INSIDE   (7 | (1 << 8))
#define MAP_SNOWDRIFT_FOREST       (8 | (1 << 8))
#define MAP_MUDDY_UNDERPASS        (9 | (1 << 8))
#define MAP_UNDERWATER             (10 | (1 << 8))
#define MAP_DESERT_CAVERNS         (11 | (1 << 8))
#define MAP_DESERT_PASS            (12 | (1 << 8))
#define MAP_SSCORAL_CORRIDORS_1F   (13 | (1 << 8))
#define MAP_SSCORAL_DECK           (14 | (1 << 8))

// gMapGroup_DarkfireIslands
#define MAP_HORIZON_ISLAND                  (0 | (2 << 8))
#define MAP_HORIZON_ISLAND_NORTH_COAST      (1 | (2 << 8))
#define MAP_HORIZON_ISLAND_SOUTH_COAST      (2 | (2 << 8))
#define MAP_HORIZON_ISLAND_SOUTH_COAST_PEAK (3 | (2 << 8))
#define MAP_HORIZON_ISLAND_JUNGLE           (4 | (2 << 8))
#define MAP_HORIZON_ISLAND_JUNGLE_PEAK      (5 | (2 << 8))
#define MAP_OCCA_ISLAND_PORT                (6 | (2 << 8))

// gMapGroup_DarkfireIslandDungeons
#define MAP_MT_PROBO_PEAK     (0 | (3 << 8))
#define MAP_MT_PROBO_CAVE_1F  (1 | (3 << 8))
#define MAP_MT_PROBO          (2 | (3 << 8))
#define MAP_MT_PROBO_CAVE_2F  (3 | (3 << 8))
#define MAP_MT_PROBO_TEMPLE   (4 | (3 << 8))
#define MAP_MT_PROBO_ENTRANCE (5 | (3 << 8))

// gMapGroup_DarkfireGrottos
#define MAP_ROUTE4EAST_TREE_GROTTO (0 | (4 << 8))

// gMapGroup_DarkfireSpecialAreas
#define MAP_ARCTIC_BAY      (0 | (5 << 8))
#define MAP_NIGHTMARE_HALL  (1 | (5 << 8))
#define MAP_FORESTS_HEART   (2 | (5 << 8))
#define MAP_SOUL_PEAK       (3 | (5 << 8))
#define MAP_CHARRED_SUMMIT  (4 | (5 << 8))
#define MAP_CHARRED_PATH    (5 | (5 << 8))
#define MAP_THUNDER_CREST   (6 | (5 << 8))
#define MAP_NORTHSTAR_ARENA (7 | (5 << 8))

// gMapGroup_IndoorChandra
#define MAP_CHANDRA_VILLAGE_PLAYER_HOUSE_1F (0 | (6 << 8))
#define MAP_CHANDRA_VILLAGE_PLAYER_HOUSE_2F (1 | (6 << 8))
#define MAP_CHANDRA_VILLAGE_TYLER_HOUSE_1F  (2 | (6 << 8))
#define MAP_CHANDRA_VILLAGE_TYLER_HOUSE_2F  (3 | (6 << 8))
#define MAP_CHANDRA_VILLAGE_LAB             (4 | (6 << 8))

// gMapGroup_IndoorSunrise
#define MAP_SUNRISE_TOWN_HOUSE1            (0 | (7 << 8))
#define MAP_SUNRISE_TOWN_HOUSE2            (1 | (7 << 8))
#define MAP_SUNRISE_TOWN_HOTEL_1F          (2 | (7 << 8))
#define MAP_SUNRISE_TOWN_POKEMON_CENTER_1F (3 | (7 << 8))
#define MAP_SUNRISE_TOWN_MART              (4 | (7 << 8))

// gMapGroup_IndoorUnion
#define MAP_UNION_CITY_HOUSE1_1F                 (0 | (8 << 8))
#define MAP_UNION_CITY_HOUSE1_2F                 (1 | (8 << 8))
#define MAP_UNION_CITY_HOUSE1_3F                 (2 | (8 << 8))
#define MAP_UNION_CITY_HOUSE2                    (3 | (8 << 8))
#define MAP_UNION_CITY_HOUSE3_1F                 (4 | (8 << 8))
#define MAP_UNION_CITY_HOUSE3_2F                 (5 | (8 << 8))
#define MAP_UNION_CITY_GOV_OFFICE_1F             (6 | (8 << 8))
#define MAP_UNION_CITY_GOV_OFFICE_2F             (7 | (8 << 8))
#define MAP_UNION_CITY_GOV_OFFICE_3F             (8 | (8 << 8))
#define MAP_UNION_CITY_ABANDONED_MUSEUM          (9 | (8 << 8))
#define MAP_UNION_CITY_BIKE_SHOP                 (10 | (8 << 8))
#define MAP_UNION_CITY_GAME_CORNER               (11 | (8 << 8))
#define MAP_UNION_CITY_POKEMON_CENTER_1F         (12 | (8 << 8))
#define MAP_UNION_CITY_DEPARTMENT_STORE_1F       (13 | (8 << 8))
#define MAP_UNION_CITY_DEPARTMENT_STORE_2F       (14 | (8 << 8))
#define MAP_UNION_CITY_DEPARTMENT_STORE_3F       (15 | (8 << 8))
#define MAP_UNION_CITY_DEPARTMENT_STORE_4F       (16 | (8 << 8))
#define MAP_UNION_CITY_DEPARTMENT_STORE_5F       (17 | (8 << 8))
#define MAP_UNION_CITY_DEPARTMENT_STORE_ELEVATOR (18 | (8 << 8))

// gMapGroup_IndoorGreendale
#define MAP_GREENDALE_VILLAGE_HOUSE1            (0 | (9 << 8))
#define MAP_GREENDALE_VILLAGE_ROSE_HOUSE        (1 | (9 << 8))
#define MAP_GREENDALE_VILLAGE_TRAINER_SCHOOL    (2 | (9 << 8))
#define MAP_GREENDALE_VILLAGE_POKEMON_CENTER_1F (3 | (9 << 8))
#define MAP_GREENDALE_VILLAGE_MART              (4 | (9 << 8))

// gMapGroup_IndoorAnheim
#define MAP_ANHEIM_TOWN_HOUSE1            (0 | (10 << 8))
#define MAP_ANHEIM_TOWN_HOUSE2            (1 | (10 << 8))
#define MAP_ANHEIM_TOWN_HOUSE3            (2 | (10 << 8))
#define MAP_ANHEIM_TOWN_POKEMON_CENTER_1F (3 | (10 << 8))
#define MAP_ANHEIM_TOWN_MART              (4 | (10 << 8))

// gMapGroup_IndoorLaveria
#define MAP_LAVERIA_CITY_HOUSE1            (0 | (11 << 8))
#define MAP_LAVERIA_CITY_HOUSE2            (1 | (11 << 8))
#define MAP_LAVERIA_CITY_POKEMON_CENTER_1F (2 | (11 << 8))
#define MAP_LAVERIA_CITY_MART              (3 | (11 << 8))
#define MAP_LAVERIA_CITY_HOUSE3            (4 | (11 << 8))
#define MAP_LAVERIA_CITY_HOUSE4            (5 | (11 << 8))

// gMapGroup_IndoorHighwind
#define MAP_HIGHWIND_VILLAGE_HOUSE1            (0 | (12 << 8))
#define MAP_HIGHWIND_VILLAGE_HOUSE2            (1 | (12 << 8))
#define MAP_HIGHWIND_VILLAGE_RANGERS_LODGE     (2 | (12 << 8))
#define MAP_HIGHWIND_VILLAGE_POKEMON_CENTER_1F (3 | (12 << 8))
#define MAP_HIGHWIND_VILLAGE_MART              (4 | (12 << 8))

// gMapGroup_IndoorNorthstar
#define MAP_NORTHSTAR_CITY_HOUSE1            (0 | (13 << 8))
#define MAP_NORTHSTAR_CITY_HOUSE2            (1 | (13 << 8))
#define MAP_NORTHSTAR_CITY_HOUSE3            (2 | (13 << 8))
#define MAP_NORTHSTAR_CITY_APARTMENTS        (3 | (13 << 8))
#define MAP_NORTHSTAR_CITY_TRAINER_SCHOOL    (4 | (13 << 8))
#define MAP_NORTHSTAR_CITY_STORAGE_FACILITY  (5 | (13 << 8))
#define MAP_NORTHSTAR_CITY_SHIPPING_CENTER   (6 | (13 << 8))
#define MAP_NORTHSTAR_CITY_TOURNAMENT_1F     (7 | (13 << 8))
#define MAP_NORTHSTAR_CITY_TOURNAMENT_2F     (8 | (13 << 8))
#define MAP_NORTHSTAR_CITY_TOURNAMENT_3F     (9 | (13 << 8))
#define MAP_NORTHSTAR_CITY_TOURNAMENT_4F     (10 | (13 << 8))
#define MAP_NORTHSTAR_CITY_LIGHTHOUSE        (11 | (13 << 8))
#define MAP_NORTHSTAR_CITY_TELESCOPE_SEA     (12 | (13 << 8))
#define MAP_NORTHSTAR_CITY_POKEMON_CENTER_1F (13 | (13 << 8))
#define MAP_NORTHSTAR_CITY_MART              (14 | (13 << 8))

// gMapGroup_IndoorPinleaf
#define MAP_PINLEAF_TOWN_HOUSE1           (0 | (14 << 8))
#define MAP_PINLEAF_TOWN_HOUSE2           (1 | (14 << 8))
#define MAP_PINLEAF_TOWN_HOUSE3           (2 | (14 << 8))
#define MAP_PINLEAF_TOWN_HOUSE4           (3 | (14 << 8))
#define MAP_PINLEAF_TOWN_HOUSE5           (4 | (14 << 8))
#define MAP_PINLEAF_TOWN_FARM_HOUSE       (5 | (14 << 8))
#define MAP_PINLEAF_TOWN_STORAGE_FACILITY (6 | (14 << 8))
#define MAP_PINLEAF_TOWN_FLOWER_SHOP      (7 | (14 << 8))
#define MAP_PINLEAF_TOWN_INN_1F           (8 | (14 << 8))
#define MAP_PINLEAF_TOWN_INN_2F           (9 | (14 << 8))
#define MAP_PINLEAF_TOWN_MART             (10 | (14 << 8))

// gMapGroup_IndoorPort
#define MAP_PORT_HARBOUR (0 | (15 << 8))

// gMapGroup_IndoorLumeria

// gMapGroup_IndoorRoute3
#define MAP_ROUTE3_HOUSE1 (0 | (17 << 8))

// gMapGroup_IndoorRoute4
#define MAP_ROUTE4_POKEMON_DAY_CARE (0 | (18 << 8))

// gMapGroup_IndoorRoute5
#define MAP_ROUTE5_HOUSE1 (0 | (19 << 8))

// gMapGroup_IndoorRoute9
#define MAP_ROUTE9_STARTER_DOME (0 | (20 << 8))

// gMapGroup_IndoorRoute11
#define MAP_ROUTE11_HOUSE1 (0 | (21 << 8))

// gMapGroup_IndoorAnheimForest
#define MAP_ANHEIM_FOREST_HOUSE1 (0 | (22 << 8))

// gMapGroup_DarkfireMapInterlinks
#define MAP_LAVERIA_CITY_INTERLINK   (0 | (23 << 8))
#define MAP_UNION_CITY_INTERLINK     (1 | (23 << 8))
#define MAP_NORTHSTAR_CITY_INTERLINK (2 | (23 << 8))

// gMapGroup_TownsAndRoutes
#define MAP_PETALBURG_CITY      (0 | (24 << 8))
#define MAP_SLATEPORT_CITY      (1 | (24 << 8))
#define MAP_MAUVILLE_CITY       (2 | (24 << 8))
#define MAP_RUSTBORO_CITY       (3 | (24 << 8))
#define MAP_FORTREE_CITY        (4 | (24 << 8))
#define MAP_LILYCOVE_CITY       (5 | (24 << 8))
#define MAP_MOSSDEEP_CITY       (6 | (24 << 8))
#define MAP_SOOTOPOLIS_CITY     (7 | (24 << 8))
#define MAP_EVER_GRANDE_CITY    (8 | (24 << 8))
#define MAP_LITTLEROOT_TOWN     (9 | (24 << 8))
#define MAP_OLDALE_TOWN         (10 | (24 << 8))
#define MAP_DEWFORD_TOWN        (11 | (24 << 8))
#define MAP_LAVARIDGE_TOWN      (12 | (24 << 8))
#define MAP_FALLARBOR_TOWN      (13 | (24 << 8))
#define MAP_VERDANTURF_TOWN     (14 | (24 << 8))
#define MAP_PACIFIDLOG_TOWN     (15 | (24 << 8))
#define MAP_ROUTE101            (16 | (24 << 8))
#define MAP_ROUTE102            (17 | (24 << 8))
#define MAP_ROUTE103            (18 | (24 << 8))
#define MAP_ROUTE104            (19 | (24 << 8))
#define MAP_ROUTE105            (20 | (24 << 8))
#define MAP_ROUTE106            (21 | (24 << 8))
#define MAP_ROUTE107            (22 | (24 << 8))
#define MAP_ROUTE108            (23 | (24 << 8))
#define MAP_ROUTE109            (24 | (24 << 8))
#define MAP_ROUTE110            (25 | (24 << 8))
#define MAP_ROUTE111            (26 | (24 << 8))
#define MAP_ROUTE112            (27 | (24 << 8))
#define MAP_ROUTE113            (28 | (24 << 8))
#define MAP_ROUTE114            (29 | (24 << 8))
#define MAP_ROUTE115            (30 | (24 << 8))
#define MAP_ROUTE116            (31 | (24 << 8))
#define MAP_ROUTE117            (32 | (24 << 8))
#define MAP_ROUTE118            (33 | (24 << 8))
#define MAP_ROUTE119            (34 | (24 << 8))
#define MAP_ROUTE120            (35 | (24 << 8))
#define MAP_ROUTE121            (36 | (24 << 8))
#define MAP_ROUTE122            (37 | (24 << 8))
#define MAP_ROUTE123            (38 | (24 << 8))
#define MAP_ROUTE124            (39 | (24 << 8))
#define MAP_ROUTE125            (40 | (24 << 8))
#define MAP_ROUTE126            (41 | (24 << 8))
#define MAP_ROUTE127            (42 | (24 << 8))
#define MAP_ROUTE128            (43 | (24 << 8))
#define MAP_ROUTE129            (44 | (24 << 8))
#define MAP_ROUTE130            (45 | (24 << 8))
#define MAP_ROUTE131            (46 | (24 << 8))
#define MAP_ROUTE132            (47 | (24 << 8))
#define MAP_ROUTE133            (48 | (24 << 8))
#define MAP_ROUTE134            (49 | (24 << 8))
#define MAP_UNDERWATER_ROUTE124 (50 | (24 << 8))
#define MAP_UNDERWATER_ROUTE126 (51 | (24 << 8))
#define MAP_UNDERWATER_ROUTE127 (52 | (24 << 8))
#define MAP_UNDERWATER_ROUTE128 (53 | (24 << 8))
#define MAP_UNDERWATER_ROUTE129 (54 | (24 << 8))
#define MAP_UNDERWATER_ROUTE105 (55 | (24 << 8))
#define MAP_UNDERWATER_ROUTE125 (56 | (24 << 8))

// gMapGroup_IndoorLittleroot
#define MAP_LITTLEROOT_TOWN_BRENDANS_HOUSE_1F    (0 | (25 << 8))
#define MAP_LITTLEROOT_TOWN_BRENDANS_HOUSE_2F    (1 | (25 << 8))
#define MAP_LITTLEROOT_TOWN_MAYS_HOUSE_1F        (2 | (25 << 8))
#define MAP_LITTLEROOT_TOWN_MAYS_HOUSE_2F        (3 | (25 << 8))
#define MAP_LITTLEROOT_TOWN_PROFESSOR_BIRCHS_LAB (4 | (25 << 8))

// gMapGroup_IndoorOldale
#define MAP_OLDALE_TOWN_HOUSE1            (0 | (26 << 8))
#define MAP_OLDALE_TOWN_HOUSE2            (1 | (26 << 8))
#define MAP_OLDALE_TOWN_POKEMON_CENTER_1F (2 | (26 << 8))
#define MAP_OLDALE_TOWN_POKEMON_CENTER_2F (3 | (26 << 8))
#define MAP_OLDALE_TOWN_MART              (4 | (26 << 8))

// gMapGroup_IndoorDewford
#define MAP_DEWFORD_TOWN_HOUSE1            (0 | (27 << 8))
#define MAP_DEWFORD_TOWN_POKEMON_CENTER_1F (1 | (27 << 8))
#define MAP_DEWFORD_TOWN_POKEMON_CENTER_2F (2 | (27 << 8))
#define MAP_DEWFORD_TOWN_GYM               (3 | (27 << 8))
#define MAP_DEWFORD_TOWN_HALL              (4 | (27 << 8))
#define MAP_DEWFORD_TOWN_HOUSE2            (5 | (27 << 8))

// gMapGroup_IndoorLavaridge
#define MAP_LAVARIDGE_TOWN_HERB_SHOP         (0 | (28 << 8))
#define MAP_LAVARIDGE_TOWN_GYM_1F            (1 | (28 << 8))
#define MAP_LAVARIDGE_TOWN_GYM_B1F           (2 | (28 << 8))
#define MAP_LAVARIDGE_TOWN_HOUSE             (3 | (28 << 8))
#define MAP_LAVARIDGE_TOWN_MART              (4 | (28 << 8))
#define MAP_LAVARIDGE_TOWN_POKEMON_CENTER_1F (5 | (28 << 8))
#define MAP_LAVARIDGE_TOWN_POKEMON_CENTER_2F (6 | (28 << 8))

// gMapGroup_IndoorFallarbor
#define MAP_FALLARBOR_TOWN_MART                    (0 | (29 << 8))
#define MAP_FALLARBOR_TOWN_BATTLE_TENT_LOBBY       (1 | (29 << 8))
#define MAP_FALLARBOR_TOWN_BATTLE_TENT_CORRIDOR    (2 | (29 << 8))
#define MAP_FALLARBOR_TOWN_BATTLE_TENT_BATTLE_ROOM (3 | (29 << 8))
#define MAP_FALLARBOR_TOWN_POKEMON_CENTER_1F       (4 | (29 << 8))
#define MAP_FALLARBOR_TOWN_POKEMON_CENTER_2F       (5 | (29 << 8))
#define MAP_FALLARBOR_TOWN_COZMOS_HOUSE            (6 | (29 << 8))
#define MAP_FALLARBOR_TOWN_MOVE_RELEARNERS_HOUSE   (7 | (29 << 8))

// gMapGroup_IndoorVerdanturf
#define MAP_VERDANTURF_TOWN_BATTLE_TENT_LOBBY       (0 | (30 << 8))
#define MAP_VERDANTURF_TOWN_BATTLE_TENT_CORRIDOR    (1 | (30 << 8))
#define MAP_VERDANTURF_TOWN_BATTLE_TENT_BATTLE_ROOM (2 | (30 << 8))
#define MAP_VERDANTURF_TOWN_MART                    (3 | (30 << 8))
#define MAP_VERDANTURF_TOWN_POKEMON_CENTER_1F       (4 | (30 << 8))
#define MAP_VERDANTURF_TOWN_POKEMON_CENTER_2F       (5 | (30 << 8))
#define MAP_VERDANTURF_TOWN_WANDAS_HOUSE            (6 | (30 << 8))
#define MAP_VERDANTURF_TOWN_FRIENDSHIP_RATERS_HOUSE (7 | (30 << 8))
#define MAP_VERDANTURF_TOWN_HOUSE                   (8 | (30 << 8))

// gMapGroup_IndoorPacifidlog
#define MAP_PACIFIDLOG_TOWN_POKEMON_CENTER_1F (0 | (31 << 8))
#define MAP_PACIFIDLOG_TOWN_POKEMON_CENTER_2F (1 | (31 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE1            (2 | (31 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE2            (3 | (31 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE3            (4 | (31 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE4            (5 | (31 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE5            (6 | (31 << 8))

// gMapGroup_IndoorPetalburg
#define MAP_PETALBURG_CITY_WALLYS_HOUSE      (0 | (32 << 8))
#define MAP_PETALBURG_CITY_GYM               (1 | (32 << 8))
#define MAP_PETALBURG_CITY_HOUSE1            (2 | (32 << 8))
#define MAP_PETALBURG_CITY_HOUSE2            (3 | (32 << 8))
#define MAP_PETALBURG_CITY_POKEMON_CENTER_1F (4 | (32 << 8))
#define MAP_PETALBURG_CITY_POKEMON_CENTER_2F (5 | (32 << 8))
#define MAP_PETALBURG_CITY_MART              (6 | (32 << 8))

// gMapGroup_IndoorSlateport
#define MAP_SLATEPORT_CITY_STERNS_SHIPYARD_1F      (0 | (33 << 8))
#define MAP_SLATEPORT_CITY_STERNS_SHIPYARD_2F      (1 | (33 << 8))
#define MAP_SLATEPORT_CITY_BATTLE_TENT_LOBBY       (2 | (33 << 8))
#define MAP_SLATEPORT_CITY_BATTLE_TENT_CORRIDOR    (3 | (33 << 8))
#define MAP_SLATEPORT_CITY_BATTLE_TENT_BATTLE_ROOM (4 | (33 << 8))
#define MAP_SLATEPORT_CITY_NAME_RATERS_HOUSE       (5 | (33 << 8))
#define MAP_SLATEPORT_CITY_POKEMON_FAN_CLUB        (6 | (33 << 8))
#define MAP_SLATEPORT_CITY_OCEANIC_MUSEUM_1F       (7 | (33 << 8))
#define MAP_SLATEPORT_CITY_OCEANIC_MUSEUM_2F       (8 | (33 << 8))
#define MAP_SLATEPORT_CITY_HARBOR                  (9 | (33 << 8))
#define MAP_SLATEPORT_CITY_HOUSE                   (10 | (33 << 8))
#define MAP_SLATEPORT_CITY_POKEMON_CENTER_1F       (11 | (33 << 8))
#define MAP_SLATEPORT_CITY_POKEMON_CENTER_2F       (12 | (33 << 8))
#define MAP_SLATEPORT_CITY_MART                    (13 | (33 << 8))

// gMapGroup_IndoorMauville
#define MAP_MAUVILLE_CITY_GYM               (0 | (34 << 8))
#define MAP_MAUVILLE_CITY_BIKE_SHOP         (1 | (34 << 8))
#define MAP_MAUVILLE_CITY_HOUSE1            (2 | (34 << 8))
#define MAP_MAUVILLE_CITY_GAME_CORNER       (3 | (34 << 8))
#define MAP_MAUVILLE_CITY_HOUSE2            (4 | (34 << 8))
#define MAP_MAUVILLE_CITY_POKEMON_CENTER_1F (5 | (34 << 8))
#define MAP_MAUVILLE_CITY_POKEMON_CENTER_2F (6 | (34 << 8))
#define MAP_MAUVILLE_CITY_MART              (7 | (34 << 8))

// gMapGroup_IndoorRustboro
#define MAP_RUSTBORO_CITY_DEVON_CORP_1F     (0 | (35 << 8))
#define MAP_RUSTBORO_CITY_DEVON_CORP_2F     (1 | (35 << 8))
#define MAP_RUSTBORO_CITY_DEVON_CORP_3F     (2 | (35 << 8))
#define MAP_RUSTBORO_CITY_GYM               (3 | (35 << 8))
#define MAP_RUSTBORO_CITY_POKEMON_SCHOOL    (4 | (35 << 8))
#define MAP_RUSTBORO_CITY_POKEMON_CENTER_1F (5 | (35 << 8))
#define MAP_RUSTBORO_CITY_POKEMON_CENTER_2F (6 | (35 << 8))
#define MAP_RUSTBORO_CITY_MART              (7 | (35 << 8))
#define MAP_RUSTBORO_CITY_FLAT1_1F          (8 | (35 << 8))
#define MAP_RUSTBORO_CITY_FLAT1_2F          (9 | (35 << 8))
#define MAP_RUSTBORO_CITY_HOUSE1            (10 | (35 << 8))
#define MAP_RUSTBORO_CITY_CUTTERS_HOUSE     (11 | (35 << 8))
#define MAP_RUSTBORO_CITY_HOUSE2            (12 | (35 << 8))
#define MAP_RUSTBORO_CITY_FLAT2_1F          (13 | (35 << 8))
#define MAP_RUSTBORO_CITY_FLAT2_2F          (14 | (35 << 8))
#define MAP_RUSTBORO_CITY_FLAT2_3F          (15 | (35 << 8))
#define MAP_RUSTBORO_CITY_HOUSE3            (16 | (35 << 8))

// gMapGroup_IndoorFortree
#define MAP_FORTREE_CITY_HOUSE1            (0 | (36 << 8))
#define MAP_FORTREE_CITY_GYM               (1 | (36 << 8))
#define MAP_FORTREE_CITY_POKEMON_CENTER_1F (2 | (36 << 8))
#define MAP_FORTREE_CITY_POKEMON_CENTER_2F (3 | (36 << 8))
#define MAP_FORTREE_CITY_MART              (4 | (36 << 8))
#define MAP_FORTREE_CITY_HOUSE2            (5 | (36 << 8))
#define MAP_FORTREE_CITY_HOUSE3            (6 | (36 << 8))
#define MAP_FORTREE_CITY_HOUSE4            (7 | (36 << 8))
#define MAP_FORTREE_CITY_HOUSE5            (8 | (36 << 8))
#define MAP_FORTREE_CITY_DECORATION_SHOP   (9 | (36 << 8))

// gMapGroup_IndoorLilycove
#define MAP_LILYCOVE_CITY_COVE_LILY_MOTEL_1F        (0 | (37 << 8))
#define MAP_LILYCOVE_CITY_COVE_LILY_MOTEL_2F        (1 | (37 << 8))
#define MAP_LILYCOVE_CITY_LILYCOVE_MUSEUM_1F        (2 | (37 << 8))
#define MAP_LILYCOVE_CITY_LILYCOVE_MUSEUM_2F        (3 | (37 << 8))
#define MAP_LILYCOVE_CITY_CONTEST_LOBBY             (4 | (37 << 8))
#define MAP_LILYCOVE_CITY_CONTEST_HALL              (5 | (37 << 8))
#define MAP_LILYCOVE_CITY_POKEMON_CENTER_1F         (6 | (37 << 8))
#define MAP_LILYCOVE_CITY_POKEMON_CENTER_2F         (7 | (37 << 8))
#define MAP_LILYCOVE_CITY_UNUSED_MART               (8 | (37 << 8))
#define MAP_LILYCOVE_CITY_POKEMON_TRAINER_FAN_CLUB  (9 | (37 << 8))
#define MAP_LILYCOVE_CITY_HARBOR                    (10 | (37 << 8))
#define MAP_LILYCOVE_CITY_MOVE_DELETERS_HOUSE       (11 | (37 << 8))
#define MAP_LILYCOVE_CITY_HOUSE1                    (12 | (37 << 8))
#define MAP_LILYCOVE_CITY_HOUSE2                    (13 | (37 << 8))
#define MAP_LILYCOVE_CITY_HOUSE3                    (14 | (37 << 8))
#define MAP_LILYCOVE_CITY_HOUSE4                    (15 | (37 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_1F       (16 | (37 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_2F       (17 | (37 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_3F       (18 | (37 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_4F       (19 | (37 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_5F       (20 | (37 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_ROOFTOP  (21 | (37 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_ELEVATOR (22 | (37 << 8))

// gMapGroup_IndoorMossdeep
#define MAP_MOSSDEEP_CITY_GYM               (0 | (38 << 8))
#define MAP_MOSSDEEP_CITY_HOUSE1            (1 | (38 << 8))
#define MAP_MOSSDEEP_CITY_HOUSE2            (2 | (38 << 8))
#define MAP_MOSSDEEP_CITY_POKEMON_CENTER_1F (3 | (38 << 8))
#define MAP_MOSSDEEP_CITY_POKEMON_CENTER_2F (4 | (38 << 8))
#define MAP_MOSSDEEP_CITY_MART              (5 | (38 << 8))
#define MAP_MOSSDEEP_CITY_HOUSE3            (6 | (38 << 8))
#define MAP_MOSSDEEP_CITY_STEVENS_HOUSE     (7 | (38 << 8))
#define MAP_MOSSDEEP_CITY_HOUSE4            (8 | (38 << 8))
#define MAP_MOSSDEEP_CITY_SPACE_CENTER_1F   (9 | (38 << 8))
#define MAP_MOSSDEEP_CITY_SPACE_CENTER_2F   (10 | (38 << 8))
#define MAP_MOSSDEEP_CITY_GAME_CORNER_1F    (11 | (38 << 8))
#define MAP_MOSSDEEP_CITY_GAME_CORNER_B1F   (12 | (38 << 8))

// gMapGroup_IndoorSootopolis
#define MAP_SOOTOPOLIS_CITY_GYM_1F                   (0 | (39 << 8))
#define MAP_SOOTOPOLIS_CITY_GYM_B1F                  (1 | (39 << 8))
#define MAP_SOOTOPOLIS_CITY_POKEMON_CENTER_1F        (2 | (39 << 8))
#define MAP_SOOTOPOLIS_CITY_POKEMON_CENTER_2F        (3 | (39 << 8))
#define MAP_SOOTOPOLIS_CITY_MART                     (4 | (39 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE1                   (5 | (39 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE2                   (6 | (39 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE3                   (7 | (39 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE4                   (8 | (39 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE5                   (9 | (39 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE6                   (10 | (39 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE7                   (11 | (39 << 8))
#define MAP_SOOTOPOLIS_CITY_LOTAD_AND_SEEDOT_HOUSE   (12 | (39 << 8))
#define MAP_SOOTOPOLIS_CITY_MYSTERY_EVENTS_HOUSE_1F  (13 | (39 << 8))
#define MAP_SOOTOPOLIS_CITY_MYSTERY_EVENTS_HOUSE_B1F (14 | (39 << 8))

// gMapGroup_IndoorEverGrande
#define MAP_EVER_GRANDE_CITY_SIDNEYS_ROOM      (0 | (40 << 8))
#define MAP_EVER_GRANDE_CITY_PHOEBES_ROOM      (1 | (40 << 8))
#define MAP_EVER_GRANDE_CITY_GLACIAS_ROOM      (2 | (40 << 8))
#define MAP_EVER_GRANDE_CITY_DRAKES_ROOM       (3 | (40 << 8))
#define MAP_EVER_GRANDE_CITY_CHAMPIONS_ROOM    (4 | (40 << 8))
#define MAP_EVER_GRANDE_CITY_HALL1             (5 | (40 << 8))
#define MAP_EVER_GRANDE_CITY_HALL2             (6 | (40 << 8))
#define MAP_EVER_GRANDE_CITY_HALL3             (7 | (40 << 8))
#define MAP_EVER_GRANDE_CITY_HALL4             (8 | (40 << 8))
#define MAP_EVER_GRANDE_CITY_HALL5             (9 | (40 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_LEAGUE_1F (10 | (40 << 8))
#define MAP_EVER_GRANDE_CITY_HALL_OF_FAME      (11 | (40 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_CENTER_1F (12 | (40 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_CENTER_2F (13 | (40 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_LEAGUE_2F (14 | (40 << 8))

// gMapGroup_IndoorRoute104
#define MAP_ROUTE104_MR_BRINEYS_HOUSE         (0 | (41 << 8))
#define MAP_ROUTE104_PRETTY_PETAL_FLOWER_SHOP (1 | (41 << 8))

// gMapGroup_IndoorRoute111
#define MAP_ROUTE111_WINSTRATE_FAMILYS_HOUSE (0 | (42 << 8))
#define MAP_ROUTE111_OLD_LADYS_REST_STOP     (1 | (42 << 8))

// gMapGroup_IndoorRoute112
#define MAP_ROUTE112_CABLE_CAR_STATION   (0 | (43 << 8))
#define MAP_MT_CHIMNEY_CABLE_CAR_STATION (1 | (43 << 8))

// gMapGroup_IndoorRoute114
#define MAP_ROUTE114_FOSSIL_MANIACS_HOUSE  (0 | (44 << 8))
#define MAP_ROUTE114_FOSSIL_MANIACS_TUNNEL (1 | (44 << 8))
#define MAP_ROUTE114_LANETTES_HOUSE        (2 | (44 << 8))

// gMapGroup_IndoorRoute116
#define MAP_ROUTE116_TUNNELERS_REST_HOUSE (0 | (45 << 8))

// gMapGroup_IndoorRoute117
#define MAP_ROUTE117_POKEMON_DAY_CARE (0 | (46 << 8))

// gMapGroup_IndoorRoute121
#define MAP_ROUTE121_SAFARI_ZONE_ENTRANCE (0 | (47 << 8))

// gMapGroup_Dungeons
#define MAP_METEOR_FALLS_1F_1R                       (0 | (48 << 8))
#define MAP_METEOR_FALLS_1F_2R                       (1 | (48 << 8))
#define MAP_METEOR_FALLS_B1F_1R                      (2 | (48 << 8))
#define MAP_METEOR_FALLS_B1F_2R                      (3 | (48 << 8))
#define MAP_RUSTURF_TUNNEL                           (4 | (48 << 8))
#define MAP_UNDERWATER_SOOTOPOLIS_CITY               (5 | (48 << 8))
#define MAP_DESERT_RUINS                             (6 | (48 << 8))
#define MAP_GRANITE_CAVE_1F                          (7 | (48 << 8))
#define MAP_GRANITE_CAVE_B1F                         (8 | (48 << 8))
#define MAP_GRANITE_CAVE_B2F                         (9 | (48 << 8))
#define MAP_GRANITE_CAVE_STEVENS_ROOM                (10 | (48 << 8))
#define MAP_PETALBURG_WOODS                          (11 | (48 << 8))
#define MAP_MT_CHIMNEY                               (12 | (48 << 8))
#define MAP_JAGGED_PASS                              (13 | (48 << 8))
#define MAP_FIERY_PATH                               (14 | (48 << 8))
#define MAP_MT_PYRE_1F                               (15 | (48 << 8))
#define MAP_MT_PYRE_2F                               (16 | (48 << 8))
#define MAP_MT_PYRE_3F                               (17 | (48 << 8))
#define MAP_MT_PYRE_4F                               (18 | (48 << 8))
#define MAP_MT_PYRE_5F                               (19 | (48 << 8))
#define MAP_MT_PYRE_6F                               (20 | (48 << 8))
#define MAP_MT_PYRE_EXTERIOR                         (21 | (48 << 8))
#define MAP_MT_PYRE_SUMMIT                           (22 | (48 << 8))
#define MAP_AQUA_HIDEOUT_1F                          (23 | (48 << 8))
#define MAP_AQUA_HIDEOUT_B1F                         (24 | (48 << 8))
#define MAP_AQUA_HIDEOUT_B2F                         (25 | (48 << 8))
#define MAP_UNDERWATER_SEAFLOOR_CAVERN               (26 | (48 << 8))
#define MAP_SEAFLOOR_CAVERN_ENTRANCE                 (27 | (48 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM1                    (28 | (48 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM2                    (29 | (48 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM3                    (30 | (48 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM4                    (31 | (48 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM5                    (32 | (48 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM6                    (33 | (48 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM7                    (34 | (48 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM8                    (35 | (48 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM9                    (36 | (48 << 8))
#define MAP_CAVE_OF_ORIGIN_ENTRANCE                  (37 | (48 << 8))
#define MAP_CAVE_OF_ORIGIN_1F                        (38 | (48 << 8))
#define MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP1 (39 | (48 << 8))
#define MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP2 (40 | (48 << 8))
#define MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP3 (41 | (48 << 8))
#define MAP_CAVE_OF_ORIGIN_B1F                       (42 | (48 << 8))
#define MAP_VICTORY_ROAD_1F                          (43 | (48 << 8))
#define MAP_VICTORY_ROAD_B1F                         (44 | (48 << 8))
#define MAP_VICTORY_ROAD_B2F                         (45 | (48 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_ENTRANCE_ROOM        (46 | (48 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_INNER_ROOM           (47 | (48 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_STAIRS_ROOM          (48 | (48 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_LOWER_ROOM           (49 | (48 << 8))
#define MAP_SHOAL_CAVE_HIGH_TIDE_ENTRANCE_ROOM       (50 | (48 << 8))
#define MAP_SHOAL_CAVE_HIGH_TIDE_INNER_ROOM          (51 | (48 << 8))
#define MAP_NEW_MAUVILLE_ENTRANCE                    (52 | (48 << 8))
#define MAP_NEW_MAUVILLE_INSIDE                      (53 | (48 << 8))
#define MAP_ABANDONED_SHIP_DECK                      (54 | (48 << 8))
#define MAP_ABANDONED_SHIP_CORRIDORS_1F              (55 | (48 << 8))
#define MAP_ABANDONED_SHIP_ROOMS_1F                  (56 | (48 << 8))
#define MAP_ABANDONED_SHIP_CORRIDORS_B1F             (57 | (48 << 8))
#define MAP_ABANDONED_SHIP_ROOMS_B1F                 (58 | (48 << 8))
#define MAP_ABANDONED_SHIP_ROOMS2_B1F                (59 | (48 << 8))
#define MAP_ABANDONED_SHIP_UNDERWATER1               (60 | (48 << 8))
#define MAP_ABANDONED_SHIP_ROOM_B1F                  (61 | (48 << 8))
#define MAP_ABANDONED_SHIP_ROOMS2_1F                 (62 | (48 << 8))
#define MAP_ABANDONED_SHIP_CAPTAINS_OFFICE           (63 | (48 << 8))
#define MAP_ABANDONED_SHIP_UNDERWATER2               (64 | (48 << 8))
#define MAP_ABANDONED_SHIP_HIDDEN_FLOOR_CORRIDORS    (65 | (48 << 8))
#define MAP_ABANDONED_SHIP_HIDDEN_FLOOR_ROOMS        (66 | (48 << 8))
#define MAP_ISLAND_CAVE                              (67 | (48 << 8))
#define MAP_ANCIENT_TOMB                             (68 | (48 << 8))
#define MAP_UNDERWATER_ROUTE134                      (69 | (48 << 8))
#define MAP_UNDERWATER_SEALED_CHAMBER                (70 | (48 << 8))
#define MAP_SEALED_CHAMBER_OUTER_ROOM                (71 | (48 << 8))
#define MAP_SEALED_CHAMBER_INNER_ROOM                (72 | (48 << 8))
#define MAP_SCORCHED_SLAB                            (73 | (48 << 8))
#define MAP_AQUA_HIDEOUT_UNUSED_RUBY_MAP1            (74 | (48 << 8))
#define MAP_AQUA_HIDEOUT_UNUSED_RUBY_MAP2            (75 | (48 << 8))
#define MAP_AQUA_HIDEOUT_UNUSED_RUBY_MAP3            (76 | (48 << 8))
#define MAP_SKY_PILLAR_ENTRANCE                      (77 | (48 << 8))
#define MAP_SKY_PILLAR_OUTSIDE                       (78 | (48 << 8))
#define MAP_SKY_PILLAR_1F                            (79 | (48 << 8))
#define MAP_SKY_PILLAR_2F                            (80 | (48 << 8))
#define MAP_SKY_PILLAR_3F                            (81 | (48 << 8))
#define MAP_SKY_PILLAR_4F                            (82 | (48 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_ICE_ROOM             (83 | (48 << 8))
#define MAP_SKY_PILLAR_5F                            (84 | (48 << 8))
#define MAP_SKY_PILLAR_TOP                           (85 | (48 << 8))
#define MAP_MAGMA_HIDEOUT_1F                         (86 | (48 << 8))
#define MAP_MAGMA_HIDEOUT_2F_1R                      (87 | (48 << 8))
#define MAP_MAGMA_HIDEOUT_2F_2R                      (88 | (48 << 8))
#define MAP_MAGMA_HIDEOUT_3F_1R                      (89 | (48 << 8))
#define MAP_MAGMA_HIDEOUT_3F_2R                      (90 | (48 << 8))
#define MAP_MAGMA_HIDEOUT_4F                         (91 | (48 << 8))
#define MAP_MAGMA_HIDEOUT_3F_3R                      (92 | (48 << 8))
#define MAP_MAGMA_HIDEOUT_2F_3R                      (93 | (48 << 8))
#define MAP_MIRAGE_TOWER_1F                          (94 | (48 << 8))
#define MAP_MIRAGE_TOWER_2F                          (95 | (48 << 8))
#define MAP_MIRAGE_TOWER_3F                          (96 | (48 << 8))
#define MAP_MIRAGE_TOWER_4F                          (97 | (48 << 8))
#define MAP_DESERT_UNDERPASS                         (98 | (48 << 8))
#define MAP_ARTISAN_CAVE_B1F                         (99 | (48 << 8))
#define MAP_ARTISAN_CAVE_1F                          (100 | (48 << 8))
#define MAP_UNDERWATER_MARINE_CAVE                   (101 | (48 << 8))
#define MAP_MARINE_CAVE_ENTRANCE                     (102 | (48 << 8))
#define MAP_MARINE_CAVE_END                          (103 | (48 << 8))
#define MAP_TERRA_CAVE_ENTRANCE                      (104 | (48 << 8))
#define MAP_TERRA_CAVE_END                           (105 | (48 << 8))
#define MAP_ALTERING_CAVE                            (106 | (48 << 8))
#define MAP_METEOR_FALLS_STEVENS_CAVE                (107 | (48 << 8))

// gMapGroup_IndoorDynamic
#define MAP_SECRET_BASE_RED_CAVE1    (0 | (49 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE1  (1 | (49 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE1   (2 | (49 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE1 (3 | (49 << 8))
#define MAP_SECRET_BASE_TREE1        (4 | (49 << 8))
#define MAP_SECRET_BASE_SHRUB1       (5 | (49 << 8))
#define MAP_SECRET_BASE_RED_CAVE2    (6 | (49 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE2  (7 | (49 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE2   (8 | (49 << 8))
#define MAP_BATTLE_COLOSSEUM_2P      (9 | (49 << 8))
#define MAP_TRADE_CENTER             (10 | (49 << 8))
#define MAP_RECORD_CORNER            (11 | (49 << 8))
#define MAP_BATTLE_COLOSSEUM_4P      (12 | (49 << 8))
#define MAP_CONTEST_HALL             (13 | (49 << 8))
#define MAP_UNUSED_CONTEST_HALL1     (14 | (49 << 8))
#define MAP_UNUSED_CONTEST_HALL2     (15 | (49 << 8))
#define MAP_UNUSED_CONTEST_HALL3     (16 | (49 << 8))
#define MAP_UNUSED_CONTEST_HALL4     (17 | (49 << 8))
#define MAP_UNUSED_CONTEST_HALL5     (18 | (49 << 8))
#define MAP_UNUSED_CONTEST_HALL6     (19 | (49 << 8))
#define MAP_CONTEST_HALL_BEAUTY      (20 | (49 << 8))
#define MAP_CONTEST_HALL_TOUGH       (21 | (49 << 8))
#define MAP_CONTEST_HALL_COOL        (22 | (49 << 8))
#define MAP_CONTEST_HALL_SMART       (23 | (49 << 8))
#define MAP_CONTEST_HALL_CUTE        (24 | (49 << 8))
#define MAP_INSIDE_OF_TRUCK          (25 | (49 << 8))
#define MAP_SS_TIDAL_CORRIDOR        (26 | (49 << 8))
#define MAP_SS_TIDAL_LOWER_DECK      (27 | (49 << 8))
#define MAP_SS_TIDAL_ROOMS           (28 | (49 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE01  (29 | (49 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE02  (30 | (49 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE03  (31 | (49 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE04  (32 | (49 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE05  (33 | (49 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE06  (34 | (49 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE07  (35 | (49 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE08  (36 | (49 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE09  (37 | (49 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE10  (38 | (49 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE11  (39 | (49 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE12  (40 | (49 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE13  (41 | (49 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE14  (42 | (49 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE15  (43 | (49 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE16  (44 | (49 << 8))
#define MAP_UNION_ROOM               (45 | (49 << 8))

// gMapGroup_SpecialArea
#define MAP_SAFARI_ZONE_NORTHWEST                           (0 | (50 << 8))
#define MAP_SAFARI_ZONE_NORTH                               (1 | (50 << 8))
#define MAP_SAFARI_ZONE_SOUTHWEST                           (2 | (50 << 8))
#define MAP_SAFARI_ZONE_SOUTH                               (3 | (50 << 8))
#define MAP_BATTLE_FRONTIER_OUTSIDE_WEST                    (4 | (50 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_LOBBY              (5 | (50 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_ELEVATOR           (6 | (50 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_CORRIDOR           (7 | (50 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_BATTLE_ROOM        (8 | (50 << 8))
#define MAP_SOUTHERN_ISLAND_EXTERIOR                        (9 | (50 << 8))
#define MAP_SOUTHERN_ISLAND_INTERIOR                        (10 | (50 << 8))
#define MAP_SAFARI_ZONE_REST_HOUSE                          (11 | (50 << 8))
#define MAP_SAFARI_ZONE_NORTHEAST                           (12 | (50 << 8))
#define MAP_SAFARI_ZONE_SOUTHEAST                           (13 | (50 << 8))
#define MAP_BATTLE_FRONTIER_OUTSIDE_EAST                    (14 | (50 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_PARTNER_ROOM (15 | (50 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_CORRIDOR     (16 | (50 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_BATTLE_ROOM  (17 | (50 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_LOBBY               (18 | (50 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_CORRIDOR            (19 | (50 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_PRE_BATTLE_ROOM     (20 | (50 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_BATTLE_ROOM         (21 | (50 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_LOBBY             (22 | (50 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_CORRIDOR          (23 | (50 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_BATTLE_ROOM       (24 | (50 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_LOBBY            (25 | (50 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_FLOOR            (26 | (50 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_TOP              (27 | (50 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_LOBBY              (28 | (50 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_CORRIDOR           (29 | (50 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_BATTLE_ROOM        (30 | (50 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_LOBBY            (31 | (50 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_PRE_BATTLE_ROOM  (32 | (50 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_BATTLE_ROOM      (33 | (50 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_LOBBY               (34 | (50 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_CORRIDOR            (35 | (50 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_THREE_PATH_ROOM     (36 | (50 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_NORMAL         (37 | (50 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_FINAL          (38 | (50 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_WILD_MONS      (39 | (50 << 8))
#define MAP_BATTLE_FRONTIER_RANKING_HALL                    (40 | (50 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE1                         (41 | (50 << 8))
#define MAP_BATTLE_FRONTIER_EXCHANGE_SERVICE_CORNER         (42 | (50 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE2                         (43 | (50 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE3                         (44 | (50 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE4                         (45 | (50 << 8))
#define MAP_BATTLE_FRONTIER_SCOTTS_HOUSE                    (46 | (50 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE5                         (47 | (50 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE6                         (48 | (50 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE7                         (49 | (50 << 8))
#define MAP_BATTLE_FRONTIER_RECEPTION_GATE                  (50 | (50 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE8                         (51 | (50 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE9                         (52 | (50 << 8))
#define MAP_BATTLE_FRONTIER_POKEMON_CENTER_1F               (53 | (50 << 8))
#define MAP_BATTLE_FRONTIER_POKEMON_CENTER_2F               (54 | (50 << 8))
#define MAP_BATTLE_FRONTIER_MART                            (55 | (50 << 8))
#define MAP_FARAWAY_ISLAND_ENTRANCE                         (56 | (50 << 8))
#define MAP_FARAWAY_ISLAND_INTERIOR                         (57 | (50 << 8))
#define MAP_BIRTH_ISLAND_EXTERIOR                           (58 | (50 << 8))
#define MAP_BIRTH_ISLAND_HARBOR                             (59 | (50 << 8))
#define MAP_TRAINER_HILL_ENTRANCE                           (60 | (50 << 8))
#define MAP_TRAINER_HILL_1F                                 (61 | (50 << 8))
#define MAP_TRAINER_HILL_2F                                 (62 | (50 << 8))
#define MAP_TRAINER_HILL_3F                                 (63 | (50 << 8))
#define MAP_TRAINER_HILL_4F                                 (64 | (50 << 8))
#define MAP_TRAINER_HILL_ROOF                               (65 | (50 << 8))
#define MAP_NAVEL_ROCK_EXTERIOR                             (66 | (50 << 8))
#define MAP_NAVEL_ROCK_HARBOR                               (67 | (50 << 8))
#define MAP_NAVEL_ROCK_ENTRANCE                             (68 | (50 << 8))
#define MAP_NAVEL_ROCK_B1F                                  (69 | (50 << 8))
#define MAP_NAVEL_ROCK_FORK                                 (70 | (50 << 8))
#define MAP_NAVEL_ROCK_UP1                                  (71 | (50 << 8))
#define MAP_NAVEL_ROCK_UP2                                  (72 | (50 << 8))
#define MAP_NAVEL_ROCK_UP3                                  (73 | (50 << 8))
#define MAP_NAVEL_ROCK_UP4                                  (74 | (50 << 8))
#define MAP_NAVEL_ROCK_TOP                                  (75 | (50 << 8))
#define MAP_NAVEL_ROCK_DOWN01                               (76 | (50 << 8))
#define MAP_NAVEL_ROCK_DOWN02                               (77 | (50 << 8))
#define MAP_NAVEL_ROCK_DOWN03                               (78 | (50 << 8))
#define MAP_NAVEL_ROCK_DOWN04                               (79 | (50 << 8))
#define MAP_NAVEL_ROCK_DOWN05                               (80 | (50 << 8))
#define MAP_NAVEL_ROCK_DOWN06                               (81 | (50 << 8))
#define MAP_NAVEL_ROCK_DOWN07                               (82 | (50 << 8))
#define MAP_NAVEL_ROCK_DOWN08                               (83 | (50 << 8))
#define MAP_NAVEL_ROCK_DOWN09                               (84 | (50 << 8))
#define MAP_NAVEL_ROCK_DOWN10                               (85 | (50 << 8))
#define MAP_NAVEL_ROCK_DOWN11                               (86 | (50 << 8))
#define MAP_NAVEL_ROCK_BOTTOM                               (87 | (50 << 8))
#define MAP_TRAINER_HILL_ELEVATOR                           (88 | (50 << 8))

// gMapGroup_IndoorRoute104Prototype
#define MAP_ROUTE104_PROTOTYPE                          (0 | (51 << 8))
#define MAP_ROUTE104_PROTOTYPE_PRETTY_PETAL_FLOWER_SHOP (1 | (51 << 8))

// gMapGroup_IndoorRoute109
#define MAP_ROUTE109_SEASHORE_HOUSE (0 | (52 << 8))

// gMapGroup_IndoorRoute110
#define MAP_ROUTE110_TRICK_HOUSE_ENTRANCE                (0 | (53 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_END                     (1 | (53 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_CORRIDOR                (2 | (53 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE1                 (3 | (53 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE2                 (4 | (53 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE3                 (5 | (53 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE4                 (6 | (53 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE5                 (7 | (53 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE6                 (8 | (53 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE7                 (9 | (53 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE8                 (10 | (53 << 8))
#define MAP_ROUTE110_SEASIDE_CYCLING_ROAD_NORTH_ENTRANCE (11 | (53 << 8))
#define MAP_ROUTE110_SEASIDE_CYCLING_ROAD_SOUTH_ENTRANCE (12 | (53 << 8))

// gMapGroup_IndoorRoute113
#define MAP_ROUTE113_GLASS_WORKSHOP (0 | (54 << 8))

// gMapGroup_IndoorRoute123
#define MAP_ROUTE123_BERRY_MASTERS_HOUSE (0 | (55 << 8))

// gMapGroup_IndoorRoute119
#define MAP_ROUTE119_WEATHER_INSTITUTE_1F (0 | (56 << 8))
#define MAP_ROUTE119_WEATHER_INSTITUTE_2F (1 | (56 << 8))
#define MAP_ROUTE119_HOUSE                (2 | (56 << 8))

// gMapGroup_IndoorRoute124
#define MAP_ROUTE124_DIVING_TREASURE_HUNTERS_HOUSE (0 | (57 << 8))

#define MAP_GROUPS_COUNT 58

#endif // GUARD_CONSTANTS_MAP_GROUPS_H
