PinleafTown_House4_MapScripts::
	.byte 0

PinleafTown_House4_Maniac::
	msgbox PinleafTown_House4_Text_Maniac, MSGBOX_NPC
	end

PinleafTown_House4_Old_Lady::
	msgbox PinleafTown_House4_Text_Old_Lady, MSGBOX_NPC
	end

PinleafTown_House4_Text_Maniac:
	.string "My dream is to be a Pokémon\n"
	.string "Researcher, like Prof. Hawthorne.\p"
	.string "Maybe even work with him in the future!$"

PinleafTown_House4_Text_Old_Lady:
	.string "My son is more of a book worm than a\n"
	.string "farmer.\p"
	.string "He is studying to get into college in\n"
	.string "Union City!$"
