UnionCity_DepartmentStore_1F_MapScripts::
	.byte 0

UnionCity_DepartmentStore_1F_Pokefan_M::
	msgbox UnionCity_DepartmentStore_1F_Text_Pokefan_M, MSGBOX_NPC
	end

UnionCity_DepartmentStore_1F_Receptionist::
	msgbox UnionCity_DepartmentStore_1F_Text_Receptionist, MSGBOX_NPC
	end

UnionCity_DepartmentStore_1F_Little_Girl::
	msgbox UnionCity_DepartmentStore_1F_Text_Little_Girl, MSGBOX_NPC
	end

UnionCity_DepartmentStore_1F_Woman::
	msgbox UnionCity_DepartmentStore_1F_Text_Woman, MSGBOX_NPC
	end

UnionCity_DepartmentStore_1F_Text_Pokefan_M:
	.string "{COLOR}{BLUE}I'm buying something for my Azumarill\n"
	.string "today!$"

UnionCity_DepartmentStore_1F_Text_Receptionist:
	.string "{COLOR}{RED}Welcome to the Union City Mall!\n"
	.string "We have all a new Trainer needs!$"

UnionCity_DepartmentStore_1F_Text_Little_Girl:
	.string "{COLOR}{RED}Today my mom is going to buy me some\n"
	.string "nice furniture!$"

UnionCity_DepartmentStore_1F_Text_Woman:
	.string "{COLOR}{RED}Whenever I come to this mall, I always\n"
	.string "end up buying all sorts of random\l"
	.string "stuff because it's always so fun!$"
