UnionCity_GovOffice_2F_MapScripts::
	.byte 0

UnionCity_GovOffice_2F_Nerd_1::
	msgbox UnionCity_GovOffice_2F_Text_Nerd_1, MSGBOX_NPC
	end

UnionCity_GovOffice_2F_Nerd_2::
	msgbox UnionCity_GovOffice_2F_Text_Nerd_2, MSGBOX_NPC
	end

UnionCity_GovOffice_2F_Nerd_3::
	msgbox UnionCity_GovOffice_2F_Text_Nerd_3, MSGBOX_NPC
	end

UnionCity_GovOffice_2F_Nerd_4::
	msgbox UnionCity_GovOffice_2F_Text_Nerd_4, MSGBOX_NPC
	end

UnionCity_GovOffice_2F_Nerd_5::
	msgbox UnionCity_GovOffice_2F_Text_Nerd_5, MSGBOX_NPC
	end

UnionCity_GovOffice_2F_Nerd_6::
	msgbox UnionCity_GovOffice_2F_Text_Nerd_6, MSGBOX_NPC
	end

UnionCity_GovOffice_2F_Text_Nerd_1:
	.string "{COLOR}{BLUE}Knowledge is power.\n"
	.string "Information is liberating.\p"
	.string "Education is the premise of progress,\n"
	.string "in every society, in every family.$"

UnionCity_GovOffice_2F_Text_Nerd_2:
	.string "{COLOR}{BLUE}If we could use a Pokémon's ability to\n"
	.string "improve the quality of life, then I am\l"
	.string "sure there would be ways to use a\l"
	.string "Pokémon's ability to hurt one's life.$"

UnionCity_GovOffice_2F_Text_Nerd_3:
	.string "{COLOR}{BLUE}We're looking into the effects of\n"
	.string "Pokémon on our environment.\p"
	.string "If only there was a way to use Pokémon\n"
	.string "abilities to improve mankind…$"

UnionCity_GovOffice_2F_Text_Nerd_4:
	.string "{COLOR}{BLUE}We act as if a left-wing agenda is\n"
	.string "something we should disavow.\p"
	.string "Of course we don't have an agenda,\n"
	.string "only the bad guys have an agenda!\l"
	.string "That's why they're winning.$"

UnionCity_GovOffice_2F_Text_Nerd_5:
	.string "{COLOR}{BLUE}I am sometimes a sneaky fox and\n"
	.string "sometimes a roaring lion.\p"
	.string "The whole secret of government lies in\n"
	.string "knowing when to be one or the other.$"

UnionCity_GovOffice_2F_Text_Nerd_6:
	.string "{COLOR}{BLUE}The care of human life and happiness,\n"
	.string "and not their demise, is the first and\l"
	.string "only trait of a good government.$"
