GreendaleVillage_TrainerSchool_MapScripts::
	.byte 0

GreendaleVillage_TrainerSchool_Student_1::
	msgbox GreendaleVillage_TrainerSchool_Text_Student_1, MSGBOX_NPC
	end

GreendaleVillage_TrainerSchool_Student_2::
	msgbox GreendaleVillage_TrainerSchool_Text_Student_2, MSGBOX_NPC
	end

GreendaleVillage_TrainerSchool_Student_3::
	msgbox GreendaleVillage_TrainerSchool_Text_Student_3, MSGBOX_NPC
	end

GreendaleVillage_TrainerSchool_Student_4::
	msgbox GreendaleVillage_TrainerSchool_Text_Student_4, MSGBOX_NPC
	end

GreendaleVillage_TrainerSchool_Student_5::
	msgbox GreendaleVillage_TrainerSchool_Text_Student_5, MSGBOX_NPC
	end

GreendaleVillage_TrainerSchool_Text_Student_1:
	.string "{COLOR}{RED}A confused Pokémon will sometimes\n"
	.string "attack itself without meaning to.\p"
	.string "But once it leaves battle, it will\n"
	.string "return to normal.$"

GreendaleVillage_TrainerSchool_Text_Student_2:
	.string "{COLOR}{BLUE}A Pokémon holding a Berry will heal\n"
	.string "itself…\p"
	.string "There are many kinds of items that\n"
	.string "Pokémon can hold…$"

GreendaleVillage_TrainerSchool_Text_Student_3:
	.string "{COLOR}{BLUE}Pokémon can hold items, but they\n"
	.string "don't know what to do with man-made\l"
	.string "items like Potions.$"

GreendaleVillage_TrainerSchool_Text_Student_4:
	.string "{COLOR}{BLUE}I'm trading Pokémon right now!$"

GreendaleVillage_TrainerSchool_Text_Student_5:
	.string "{COLOR}{BLUE}Woo!\nI always wanted a Poliwag!$"
