gText_Birch_Welcome:: @ 82C897B
	.string "Hello there! How are you?\p"
	.string "Welcome to the beautiful Tenjo region!\p"
	.string "My name is Professor Hawthorne.\n"
	.string "I'm a Pokémon Researcher!\p"
	.string "$"

gText_Birch_Pokemon:: @ 82C89FB
	.string "This is what we call a “Pokémon.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech:: @ 82C8A1F
	.string "Tenjo is alive with Pokémon.\p"
	.string "Here, we live side by side with them,\n"
	.string "exploring the lush forests, sparkling\l"
	.string "rivers, and giant mountains together.\p"
	.string "We play with Pokémon, work with\n"
	.string "Pokémon, and battle with Pokémon.\p"
	.string "But even in a place as magical as\n"
	.string "Tenjo, there's still so much we don't\l"
	.string "know about Pokémon.\p"
	.string "They hold many mysteries waiting to be\n"
	.string "uncovered.\p"
	.string "That's why I've dedicated myself to\n"
	.string "becoming a Pokémon Professor.\p"
	.string "To discover all the secrets hidden\n"
	.string "within Tenjo and its Pokémon!\p"
	.string "$"

gText_Birch_AndYouAre:: @ 82C8BD0
	.string "And you are?$"

gText_Birch_BoyOrGirl:: @ 82C8BDD
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName:: @ 82C8BFF
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer:: @ 82C8C1C
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer:: @ 82C8C2A
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who lives right\n"
	.string "here in Chandra Village!\p"
	.string "$"

gText_Birch_AreYouReady:: @ 82C8C7A
	.string "All right, {PLAYER}!\n"
	.string "Are you ready?\p"
	.string "Your very own Pokémon adventure is\n"
	.string "about to begin.\p"
	.string "Take a deep breath and dive into the\n"
	.string "world of Pokémon, where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "I'll be looking forward to seeing you\n"
	.string "later, {PLAYER}.\p"
	.string "Don't forget to visit me in my Pokémon\n"
	.string "Lab!$"
