@ Contest move effect descriptions

gText_HighlyAppealingMove:: @ 827CB82
	.string "A highly appealing move.$"

gText_UserMoreEasilyStartled::
	.string "After this move, the user is\n"
	.string "more easily startled.$"

gText_GreatAppealButNoMoreToEnd::
	.string "Makes a great appeal, but\n"
	.string "allows no more to the end.$"

gText_UsedRepeatedlyWithoutBoringJudge::
	.string "Can be repeatedly used\n"
	.string "without boring the JUDGE.$"

gText_AvoidStartledByOthersOnce::
	.string "Can avoid being startled\n"
	.string "by others once.$"

gText_AvoidStartledByOthers::
	.string "Can avoid being startled\n"
	.string "by others.$"

gText_AvoidStartledByOthersLittle::
	.string "Can avoid being startled\n"
	.string "by others a little.$"

gText_UserLessLikelyStartled::
	.string "After this move, the user is\n"
	.string "less likely to be startled.$"

gText_SlightlyStartleFrontMon::
	.string "Slightly startles the\n"
	.string "POKéMON in front.$"

gText_SlightlyStartleAppealed::
	.string "Slightly startles those\n"
	.string "that have made appeals.$"

gText_StartleAppealedBeforeUser::
	.string "Startles the POKéMON that\n"
	.string "appealed before the user.$"

gText_StartleAllAppealed::
	.string "Startles all POKéMON that\n"
	.string "have done their appeals.$"

gText_BadlyStartleFrontMon::
	.string "Badly startles the\n"
	.string "POKéMON in front.$"

gText_BadlyStartleAppealed::
	.string "Badly startles those that\n"
	.string "have made appeals.$"

gText_StartleAppealedBeforeUser2::
	.string "Startles the POKéMON that\n"
	.string "appealed before the user.$"

gText_StartleAllAppealed2::
	.string "Startles all POKéMON that\n"
	.string "have done their appeals.$"

gText_ShiftJudgesAttentionFromOthers::
	.string "Shifts the JUDGE's\n"
	.string "attention from others.$"

gText_StartleMonHasJudgesAttention::
	.string "Startles the POKéMON that\n"
	.string "has the JUDGE's attention.$"

gText_JamOthersMissesTurn::
	.string "Jams the others, and misses\n"
	.string "one turn of appeals.$"

gText_StartleMonsMadeSameTypeAppeal::
	.string "Startles POKéMON that\n"
	.string "made a same-type appeal.$"

gText_BadlyStartleCoolAppeals::
	.string "Badly startles POKéMON\n"
	.string "that made COOL appeals.$"

gText_BadlyStartleBeautyAppeals::
	.string "Badly startles POKéMON\n"
	.string "that made BEAUTY appeals.$"

gText_BadlyStartleCuteAppeals::
	.string "Badly startles POKéMON\n"
	.string "that made CUTE appeals.$"

gText_BadlyStartleSmartAppeals::
	.string "Badly startles POKéMON\n"
	.string "that made SMART appeals.$"

gText_BadlyStartleToughAppeals::
	.string "Badly startles POKéMON\n"
	.string "that made TOUGH appeals.$"

gText_MakeMonAfterUserNervous::
	.string "Makes one POKéMON after\n"
	.string "the user nervous.$"

gText_MakeAllMonsAfterUserNervous::
	.string "Makes all POKéMON after\n"
	.string "the user nervous.$"

gText_WorsenConditionOfThoseMadeAppeals::
	.string "Worsens the condition of\n"
	.string "those that made appeals.$"

gText_BadlyStartleMonsGoodCondition::
	.string "Badly startles POKéMON in\n"
	.string "good condition.$"

gText_AppealGreatIfPerformedFirst::
	.string "The appeal works great if\n"
	.string "performed first.$"

gText_AppealGreatIfPerformedLast::
	.string "The appeal works great if\n"
	.string "performed last.$"

gText_AppealAsGoodAsThoseBeforeIt::
	.string "Makes the appeal as good\n"
	.string "as those before it.$"

gText_AppealAsGoodAsOneBeforeIt::
	.string "Makes the appeal as good\n"
	.string "as the one before it.$"

gText_AppealBetterLaterItsPerformed::
	.string "The appeal works better\n"
	.string "the later it is performed.$"

gText_AppealVariesDependingOnTiming::
	.string "The appeal's quality varies\n"
	.string "depending on its timing.$"

gText_WorksWellIfSameTypeAsBefore::
	.string "Works well if it's the same\n"
	.string "type as the one before.$"

gText_WorksWellIfDifferentTypeAsBefore::
	.string "Works well if different in\n"
	.string "type than the one before.$"

gText_AffectedByAppealInFront::
	.string "Affected by how well the\n"
	.string "appeal in front goes.$"

gText_UpsConditionHelpsPreventNervousness::
	.string "Ups the user's condition.\n"
	.string "Helps prevent nervousness.$"

gText_AppealWorksWellIfConditionGood::
	.string "The appeal works well if the\n"
	.string "user's condition is good.$"

gText_NextAppealMadeEarlier::
	.string "The next appeal can be\n"
	.string "made earlier next turn.$"

gText_NextAppealMadeLater::
	.string "The next appeal can be\n"
	.string "made later next turn.$"

gText_TurnOrderMoreEasilyScrambled::
	.string "Makes the next turn's order\n"
	.string "more easily scrambled.$"

gText_ScrambleOrderOfNextAppeals::
	.string "Scrambles the order of\n"
	.string "appeals on the next turn.$"

gText_AppealExcitesAudienceInAnyContest::
	.string "An appeal that excites the\n"
	.string "audience in any CONTEST.$"

gText_BadlyStartlesMonsGoodAppeals::
	.string "Badly startles all POKéMON\n"
	.string "that made good appeals.$"

gText_AppealBestMoreCrowdExcited::
	.string "The appeal works best the\n"
	.string "more the crowd is excited.$"

gText_TemporarilyStopCrowdExcited::
	.string "Temporarily stops the\n"
	.string "crowd from growing excited.$"

@ Unused move names

gText_RainDance:: @ 827D468
	.string "RAIN DANCE$"

gText_Rage:: @ 827D473
	.string "RAGE$"

gText_FocusEnergy:: @ 827D478
	.string "FOCUS ENERGY$"

gText_Hypnosis:: @ 827D485
	.string "HYPNOSIS$"

gText_Softboiled:: @ 827D48E
	.string "SOFTBOILED$"

gText_HornAttack:: @ 827D499
	.string "HORN ATTACK$"

gText_SwordsDance:: @ 827D4A5
	.string "SWORDS DANCE$"

gText_Conversion:: @ 827D4B2
	.string "CONVERSION$"

gText_SunnyDay:: @ 827D4BD
	.string "SUNNY DAY$"

gText_Rest2:: @ 827D4C7
	.string "REST$"

gText_Vicegrip:: @ 827D4CC
	.string "VICEGRIP$"

gText_DefenseCurl:: @ 827D4D5
	.string "DEFENSE CURL$"

gText_LockOn:: @ 827D4E2
	.string "LOCK-ON$"

@ Contest type names

gContestMoveTypeCoolText:: @ 827D4EA
	.string "COOL$"

gContestMoveTypeBeautyText:: @ 827D4EF
	.string "BEAUTY$"

gContestMoveTypeCuteText:: @ 827D4F6
	.string "CUTE$"

gContestMoveTypeSmartText:: @ 827D4FB
	.string "SMART$"

gContestMoveTypeToughText:: @ 827D501
	.string "TOUGH$"

gText_AppealNumWhichMoveWillBePlayed:: @ 827D507
	.string "Appeal no. {STR_VAR_1}!\n"
	.string "Which move will be played?$"

gText_AppealNumButItCantParticipate:: @ 827D531
	.string "Appeal no. {STR_VAR_1}!\n"
	.string "But it can't participate!$"

gText_MonAppealedWithMove:: @ 827D55A
	.string "{STR_VAR_1} appealed with\n"
	.string "{STR_VAR_2}!$"

gText_MonWasWatchingOthers:: @ 827D56F
	.string "{STR_VAR_1} was watching\n"
	.string "the others.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AllOutOfAppealTime:: @ 827D597
	.string "We're all out of\n"
	.string "Appeal Time!{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

@ Unused appeal result texts

gText_ButAppealWasJammed:: @ 827D5C1
	.string "But the appeal was\n"
	.string "jammed.$"

gText_FollowedAnotherMonsLead:: @ 827D5DC
	.string "It followed another\n"
	.string "POKéMON's lead.$"

gText_ButItMessedUp:: @ 827D600
	.string "But it messed up.$"

gText_WentBetterThanUsual:: @ 827D612
	.string "It went better than\n"
	.string "usual.$"

gText_JudgeLookedAwayForSomeReason:: @ 827D62D
	.string "The JUDGE looked away\n"
	.string "for some reason.$"

gText_WorkedHardToBuildOnPastMistakes:: @ 827D654
	.string "It worked hard to build on\n"
	.string "past mistakes.$"

gText_CantMakeAnyMoreMoves:: @ 827D67E
	.string "It can't make any more\n"
	.string "moves.$"

gText_WorkedFrighteninglyWell:: @ 827D69C
	.string "It worked frighteningly\n"
	.string "well.$"

gText_WorkedHardAsStandoutMon:: @ 827D6BA
	.string "It worked as hard as the\n"
	.string "standout POKéMON.$"

gText_JudgedLookedOnExpectantly:: @ 827D6E5
	.string "The JUDGE looked on\n"
	.string "expectantly.$"

gText_WorkedRatherWell:: @ 827D706
	.string "It worked rather well.$"

gText_WorkedLittleBetterThanUsual:: @ 827D71D
	.string "It worked a little better\n"
	.string "than usual.$"

@ Round result texts

gText_MonFailedToStandOutAtAll:: @ 827D743
	.string "{STR_VAR_1} failed to\n"
	.string "stand out at all…{PAUSE_UNTIL_PRESS}$"

gText_MonDidntStandOutVeryMuch:: @ 827D764
	.string "{STR_VAR_1} didn't stand\n"
	.string "out very much…{PAUSE_UNTIL_PRESS}$"

gText_MonCaughtALittleAttention:: @ 827D785
	.string "{STR_VAR_1} caught a\n"
	.string "little attention.{PAUSE_UNTIL_PRESS}$"

gText_MonAttractedALotOfAttention:: @ 827D7A5
	.string "{STR_VAR_1} attracted a\n"
	.string "lot of attention.{PAUSE_UNTIL_PRESS}$"

gText_MonCommandedTotalAttention:: @ 827D7C8
	.string "{STR_VAR_1} commanded\n"
	.string "total attention.{PAUSE_UNTIL_PRESS}$"

gText_MonHasntMadeItsAppeal:: @ 827D7E8
	.string "{STR_VAR_1} hasn't made\n"
	.string "its appeal.{PAUSE_UNTIL_PRESS}$"

@ Unused
gText_AnticipationSwelledForMonsAppealNext2:: @ 827D805
	.string "Anticipation swelled for\n"
	.string "{STR_VAR_1}'s appeal next.$"

gText_EmptyContestString:: @ 827D830
	.string "$"

gText_JudgesViewsOnMonHeldFirm:: @ 827D831
	.string "The JUDGE 's views on\n"
	.string "{STR_VAR_1} held firm.$"

gText_MonsXChangedPerceptions:: @ 827D855
	.string "{STR_VAR_1}'s {STR_VAR_3}\n"
	.string "changed perceptions.$"

gText_MonsAppealEffectWoreOff:: @ 827D872
	.string "{STR_VAR_1}'s appeal\n"
	.string "effect wore off.$"

gText_SpecialAppealsEffectWoreOff:: @ 827D88F
	.string "The special appeal's\n"
	.string "effect wore off.$"

gText_EveryonesAppealsMadeToLookSame:: @ 827D8B5
	.string "Everyone's appeals were\n"
	.string "made to look the same.$"

gText_CheapenedMonsAppeal:: @ 827D8E4
	.string "It cheapened\n"
	.string "{STR_VAR_2}'s appeal.$"

gText_CheapenedAppealOfThoseAhead:: @ 827D8FE
	.string "It cheapened the appeal\n"
	.string "of those ahead.$"

gText_StoleAttentionAwayFromMon:: @ 827D926
	.string "It stole attention away\n"
	.string "from {STR_VAR_2}.$"

gText_CheapenedMonsAppeal2:: @ 827D947
	.string "It cheapened\n"
	.string "{STR_VAR_2}'s appeal.$"

gText_SeverelyCheapenedOtherAppeals:: @ 827D961
	.string "It severely cheapened\n"
	.string "other appeals.$"

gText_AnticipationSwelledForMonsAppealNext:: @ 827D986
	.string "Anticipation swelled for\n"
	.string "{STR_VAR_1}'s appeal next.$"

gText_CheapenedAppealOfThoseAhead2:: @ 827D9B1
	.string "It cheapened the appeal\n"
	.string "of those ahead.$"

gText_CheapenedJudgesFavoriteAppeal:: @ 827D9D9
	.string "It cheapened the JUDGE's\n"
	.string "favorite appeal.$"

gText_AppealsOfOthersCheapenedByHalf:: @ 827DA03
	.string "The appeals of others\n"
	.string "were cheapened by half.$"

gText_StoodOutToMakeUpForBeingJammed:: @ 827DA31
	.string "It stood out to make up\n"
	.string "for being jammed.$"

gText_CantParticipateInAppealsAnyMore:: @ 827DA5B
	.string "It can't participate in\n"
	.string "appeals any more.$"

gText_TouchedJudgeForFantasticAppeal:: @ 827DA85
	.string "It touched the JUDGE for\n"
	.string "a fantastic appeal.$"

gText_AnticipationRoseForUpcomingAppeals:: @ 827DAB2
	.string "Anticipation rose for\n"
	.string "upcoming appeals.$"

gText_StoodOutAsMuchAsSpecialAppeals:: @ 827DADA
	.string "It stood out as much as\n"
	.string "special appeals.$"

gText_StoodOutAsMuchAsMon:: @ 827DB03
	.string "It stood out as much as\n"
	.string "{STR_VAR_1}.$"

gText_JammedAppealsMadeEvenLessNoticeable:: @ 827DB1F
	.string "Jammed appeals were made\n"
	.string "even less noticeable.$"

gText_EveryonesAppealsMadeSame:: @ 827DB4E
	.string "Everyone's appeals were\n"
	.string "made the same.$"

@ Appeal result texts

gText_BecameMoreConsciousOfOtherMons:: @ 827DB75
	.string "It became more conscious\n"
	.string "of the other POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonCantMakeAnAppealAfterThis:: @ 827DBB0
	.string "{STR_VAR_1} can't make an\n"
	.string "appeal after this.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_SettledDownJustLittleBit:: @ 827DBE0
	.string "It settled down just a\n"
	.string "little bit.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_BecameObliviousToOtherMons:: @ 827DC0F
	.string "It became oblivious to\n"
	.string "the other POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_BecameLessAwareOfOtherMons:: @ 827DC45
	.string "It became less aware of\n"
	.string "the other POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StoppedCaringAboutOtherMons:: @ 827DC7C
	.string "It stopped caring about\n"
	.string "other POKéMON much.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToStartleOtherMons:: @ 827DCB4
	.string "It tried to startle the\n"
	.string "other POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToDazzleOthers:: @ 827DCE7
	.string "It tried to dazzle the\n"
	.string "others.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_JudgeLookedAwayFromMon:: @ 827DD12
	.string "The JUDGE looked away\n"
	.string "from {STR_VAR_1}.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToUnnerveNextMon:: @ 827DD3D
	.string "It tried to unnerve the\n"
	.string "next POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonBecameNervous:: @ 827DD6F
	.string "{STR_VAR_1} became\n"
	.string "nervous.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AppealTriedToUnnerveWaitingMons:: @ 827DD8E
	.string "The appeal tried to\n"
	.string "unnerve waiting POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TauntedMonsDoingWell:: @ 827DDC7
	.string "It taunted POKéMON\n"
	.string "doing well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonRegainedItsForm:: @ 827DDF2
	.string "{STR_VAR_1} regained its\n"
	.string "form.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToJamMonDoingWell:: @ 827DE14
	.string "It tried to jam POKéMON\n"
	.string "doing well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StandoutMonHustledEvenMore:: @ 827DE44
	.string "The standout {STR_VAR_1}\n"
	.string "hustled even more.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_LargelyUnnoticedMonWorkedHard:: @ 827DE73
	.string "The largely unnoticed\n"
	.string "{STR_VAR_1} worked hard.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_WorkedAsMuchAsMonBefore:: @ 827DEA5
	.string "It worked as much as\n"
	.string "POKéMON before it.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell:: @ 827DED9
	.string "{STR_VAR_1}'s appeal did\n"
	.string "not go well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_WorkedAsMuchAsPrecedingMon:: @ 827DF02
	.string "It worked as much as the\n"
	.string "preceding POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell2:: @ 827DF3A
	.string "{STR_VAR_1}'s appeal did\n"
	.string "not go well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell3:: @ 827DF63
	.string "{STR_VAR_1}'s appeal did\n"
	.string "not go well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentSlightlyWell:: @ 827DF8C
	.string "{STR_VAR_1}'s appeal\n"
	.string "went slightly well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentPrettyWell:: @ 827DFB8
	.string "{STR_VAR_1}'s appeal\n"
	.string "went pretty well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentExcellently:: @ 827DFE2
	.string "{STR_VAR_1}'s appeal\n"
	.string "went excellently.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWasDud:: @ 827E00C
	.string "{STR_VAR_1}'s appeal was\n"
	.string "a dud.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotWorkVeryWell:: @ 827E02F
	.string "{STR_VAR_1}'s appeal did\n"
	.string "not work very well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentSlightlyWell2:: @ 827E05F
	.string "{STR_VAR_1}'s appeal\n"
	.string "went slightly well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentPrettyWell2:: @ 827E08B
	.string "{STR_VAR_1}'s appeal\n"
	.string "went pretty well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentVeryWell:: @ 827E0B5
	.string "{STR_VAR_1}'s appeal\n"
	.string "went very well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentExcellently2:: @ 827E0DD
	.string "{STR_VAR_1}'s appeal\n"
	.string "went excellently.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_SameTypeAsOneBeforeGood:: @ 827E107
	.string "It's the same type as the\n"
	.string "POKéMON before--good!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_NotSameTypeAsOneBeforeGood:: @ 827E143
	.string "It's not the same type as\n"
	.string "the one before--good!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StoodOutMuchMoreThanMonBefore:: @ 827E17F
	.string "It stood out much more\n"
	.string "than the POKéMON before.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_DidntDoAsWellAsMonBefore:: @ 827E1BB
	.string "It didn't do as well as the\n"
	.string "POKéMON before.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsConditionRoseAboveUsual:: @ 827E1F3
	.string "{STR_VAR_1}'s condition\n"
	.string "rose above usual.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsHotStatusMadeGreatAppeal:: @ 827E220
	.string "{STR_VAR_1}'s hot status\n"
	.string "made it a great appeal!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MovedUpInLineForNextAppeal:: @ 827E254
	.string "It moved up in line for\n"
	.string "the next appeal.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MovedBackInLineForNextAppeal:: @ 827E289
	.string "It moved back in line once\n"
	.string "for the next appeal.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_ScrambledUpOrderForNextTurn:: @ 827E2C5
	.string "It scrambled up the\n"
	.string "order for the next turn.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_JudgeLookedAtMonExpectantly:: @ 827E2FE
	.string "The JUDGE looked at\n"
	.string "{STR_VAR_1} expectantly.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AppealComboWentOverWell:: @ 827E32E
	.string "The appeal combo went\n"
	.string "over well.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AppealComboWentOverVeryWell:: @ 827E35B
	.string "The appeal combo went\n"
	.string "over very well.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AppealComboWentOverExcellently:: @ 827E38D
	.string "The appeal combo went\n"
	.string "over excellently.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonManagedToAvertGaze:: @ 827E3C1
	.string "{STR_VAR_1} managed to\n"
	.string "avert its gaze.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonManagedToAvoidSeeingIt:: @ 827E3EB
	.string "{STR_VAR_1} managed to\n"
	.string "avoid seeing it.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonIsntFazedByThatSortOfThing:: @ 827E416
	.string "{STR_VAR_1} isn't fazed\n"
	.string "by that sort of thing.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonBecameALittleDistracted:: @ 827E448
	.string "{STR_VAR_1} became a\n"
	.string "little distracted.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_TriedToStartleOtherPokemon:: @ 827E473
	.string "It tried to startle the\n"
	.string "other POKéMON.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonLookedDownOutOfDistraction:: @ 827E4A6
	.string "{STR_VAR_1} looked down\n"
	.string "out of distraction.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonTurnedBackOutOfDistraction:: @ 827E4D5
	.string "{STR_VAR_1} turned back\n"
	.string "out of distraction.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonCouldntHelpUtteringCry:: @ 827E504
	.string "{STR_VAR_1} couldn't help\n"
	.string "uttering a cry.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonCouldntHelpLeapingUp:: @ 827E531
	.string "{STR_VAR_1} couldn't help\n"
	.string "leaping up.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonTrippedOutOfDistraction:: @ 827E55A
	.string "{STR_VAR_1} tripped over\n"
	.string "out of distraction.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonWasTooNervousToMove:: @ 827E58A
	.string "{STR_VAR_1} was too\n"
	.string "nervous to move.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItMessedUp2:: @ 827E5B2
	.string "But it messed up.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItFailedToMakeTargetNervous:: @ 827E5D0
	.string "But it failed to make\n"
	.string "the target nervous.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItFailedToMakeAnyoneNervous:: @ 827E606
	.string "But it failed to make\n"
	.string "anyone nervous.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItWasIgnored:: @ 827E638
	.string "But it was ignored…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_CouldntImproveItsCondition:: @ 827E658
	.string "But it couldn't improve\n"
	.string "its condition…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_BadConditionResultedInWeakAppeal:: @ 827E68B
	.string "Its bad condition\n"
	.string "resulted in a weak appeal.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonWasUnaffected:: @ 827E6C4
	.string "{STR_VAR_1} was\n"
	.string "unaffected.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_RepeatedAppeal:: @ 827E6E3
	.string "{STR_VAR_1} disappointed\n"
	.string "by repeating an appeal.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsXWentOverGreat:: @ 827E717
	.string "{STR_VAR_1}'s {STR_VAR_3}\n"
	.string "went over great.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsXDidntGoOverWell:: @ 827E73C
	.string "{STR_VAR_1}'s {STR_VAR_3}\n"
	.string "didn't go over well here…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsXGotTheCrowdGoing:: @ 827E76A
	.string "{STR_VAR_1}'s {STR_VAR_3}\n"
	.string "got the crowd going.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonCantAppealNextTurn:: @ 827E793
	.string "{STR_VAR_1} can't appeal\n"
	.string "next turn…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AttractedCrowdsAttention:: @ 827E7BA
	.string "It attracted the crowd's\n"
	.string "attention.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_CrowdContinuesToWatchMon:: @ 827E7EA
	.string "The crowd continues to\n"
	.string "watch {STR_VAR_3}.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsMoveIsIgnored:: @ 827E817
	.string "{STR_VAR_1}'s\n"
	.string "{STR_VAR_2} is ignored.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_Contest_Shyness:: @ 827E837
	.string "shyness$"

gText_Contest_Anxiety:: @ 827E83F
	.string "anxiety$"

gText_Contest_Laziness:: @ 827E847
	.string "laziness$"

gText_Contest_Hesitancy:: @ 827E850
	.string "hesitancy$"

gText_Contest_Fear:: @ 827E85A
	.string "fear$"

gText_Contest_Coolness:: @ 827E85F
	.string "coolness$"

gText_Contest_Beauty:: @ 827E868
	.string "beauty$"

gText_Contest_Cuteness:: @ 827E86F
	.string "cuteness$"

gText_Contest_Smartness:: @ 827E878
	.string "smartness$"

gText_Contest_Toughness:: @ 827E882
	.string "toughness$"

@ Unused
gText_Tension:: @ 827E88C
	.string "TENSION$"

gText_CoolMove:: @ 827E894
	.string "COOL Move$"

gText_BeautyMove:: @ 827E89E
	.string "BEAUTY Move$"

gText_CuteMove:: @ 827E8AA
	.string "CUTE Move$"

gText_SmartMove:: @ 827E8B4
	.string "SMART Move$"

gText_ToughMove:: @ 827E8BF
	.string "TOUGH Move$"

gText_3QuestionMarks:: @ 827E8CA
	.string "???$"
