Text_BootUpPC: @ 827265A
	.string "{PLAYER} booted up the PC.$"

gText_WhichPCShouldBeAccessed:: @ 827266F
	.string "Which PC should be accessed?$"

gText_AccessedSomeonesPC:: @ 827268C
	.string "Accessed Pokémon PC.$"

gText_StorageSystemOpened:: @ 82726A3
	.string "Pokémon Storage System opened.$"

gText_AccessedPlayersPC:: @ 82726C2
	.string "Accessed Items PC.$"

gText_AccessedLanettesPC:: @ 82726D4
	.string "Accessed Pokémon PC.$"
