LaveriaCity_PokemonCenter_1F_MapScripts::
	.byte 0

LaveriaCity_PokemonCenter_1F_Fat_Guy::
	msgbox LaveriaCity_PokemonCenter_1F_Text_Fat_Guy, MSGBOX_NPC
	end

LaveriaCity_PokemonCenter_1F_Woman::
	msgbox LaveriaCity_PokemonCenter_1F_Text_Woman, MSGBOX_NPC
	end

LaveriaCity_PokemonCenter_1F_Bug_Catcher::
	msgbox LaveriaCity_PokemonCenter_1F_Text_Bug_Catcher, MSGBOX_NPC
	end

LaveriaCity_PokemonCenter_1F_Text_Fat_Guy:
	.string "{COLOR}{BLUE}Anyone who says that money can't buy\n"
	.string "happiness has clearly never spent\l"
	.string "their money on pizza!$"

LaveriaCity_PokemonCenter_1F_Text_Woman:
	.string "{COLOR}{RED}There are many types of Pokémon.\p"
	.string "All types have their strengths and\n"
	.string "weaknesses against other types.\p"
	.string "Depending on the types of Pokémon,\n"
	.string "a battle could be easy or hard.$"

LaveriaCity_PokemonCenter_1F_Text_Bug_Catcher:
	.string "{COLOR}{BLUE}When my Pokémon ate an\n"
	.string "Oran Berry, it regained HP!$"
