AnheimTown_Mart_MapScripts::
	.byte 0

AnheimTown_Mart_Old_Lady::
	msgbox AnheimTown_Mart_Text_Old_Lady, MSGBOX_NPC
	end

AnheimTown_Mart_Girl::
	msgbox AnheimTown_Mart_Text_Girl, MSGBOX_NPC
	end

AnheimTown_Mart_Boy::
	msgbox AnheimTown_Mart_Text_Boy, MSGBOX_NPC
	end

AnheimTown_Mart_Text_Old_Lady:
	.string "The odds of going to the store for a\n"
	.string "loaf of bread and coming out with a\l"
	.string "loaf of bread are three billion to one!$"

AnheimTown_Mart_Text_Girl:
	.string "{COLOR}{RED}When I shop, the world gets better,\n"
	.string "and the world is better, but then it's\l"
	.string "not, and I need to do it again, hehe.$"

AnheimTown_Mart_Text_Boy:
	.string "{COLOR}{BLUE}For battle, X Special is crucial.\p"
	.string "It jacks up the power of some moves\n"
	.string "even though it's only for one battle.$"
