PinleafTown_House2_MapScripts::
	.byte 0

PinleafTown_House2_Man::
	msgbox PinleafTown_House2_Text_Man, MSGBOX_NPC
	end

PinleafTown_House2_Little_Boy::
	msgbox PinleafTown_House2_Text_Little_Boy, MSGBOX_NPC
	end

PinleafTown_House2_Text_Man:
	.string "The mulch I've used for my crops this\n"
	.string "year is top-notch.\p"
	.string "Our Berries will be the largest\n"
	.string "Berries around.\p"
	.string "Even larger than the ones Mr. Mowell,\n"
	.string "next door, likes to brag about!$"

PinleafTown_House2_Text_Little_Boy:
	.string "{COLOR}{BLUE}My dad's really obsessed with beating\n"
	.string "Mr. Mowell's farm on the annual crop\l"
	.string "harvest contest.\p"
	.string "It's all he ever talks about!$"
