WaterwayCity_MapScripts::
	.byte 0

WaterwayCity_PokeFan_F_1::
	msgbox WaterwayCity_Text_PokeFan_F_1, MSGBOX_NPC
	end

WaterwayCity_Woman_5_1::
	msgbox WaterwayCity_Text_Woman_5_1, MSGBOX_NPC
	end

WaterwayCity_BlackBelt::
	msgbox WaterwayCity_Text_BlackBelt, MSGBOX_NPC
	end

WaterwayCity_Woman_4::
	msgbox WaterwayCity_Text_Woman_4, MSGBOX_NPC
	end

WaterwayCity_Man_1::
	msgbox WaterwayCity_Text_Man_1, MSGBOX_NPC
	end

WaterwayCity_Girl_2::
	msgbox WaterwayCity_Text_Girl_2, MSGBOX_NPC
	end

WaterwayCity_Cook::
	msgbox WaterwayCity_Text_Cook, MSGBOX_NPC
	end

WaterwayCity_Old_Woman::
	msgbox WaterwayCity_Text_Old_Woman, MSGBOX_NPC
	end

WaterwayCity_Girl_1::
	msgbox WaterwayCity_Text_Girl_1, MSGBOX_NPC
	end

WaterwayCity_Cameraman::
	msgbox WaterwayCity_Text_Cameraman, MSGBOX_NPC
	end

WaterwayCity_PokeFan_F_2::
	msgbox WaterwayCity_Text_PokeFan_F_2, MSGBOX_NPC
	end

WaterwayCity_Sailor::
	msgbox WaterwayCity_Text_Sailor, MSGBOX_NPC
	end

WaterwayCity_Girl_3::
	msgbox WaterwayCity_Text_Girl_3, MSGBOX_NPC
	end

WaterwayCity_Mart_Employee_1::
	msgbox WaterwayCity_Text_Mart_Employee_1, MSGBOX_NPC
	end

WaterwayCity_Old_Man::
	msgbox WaterwayCity_Text_Old_Man, MSGBOX_NPC
	end

WaterwayCity_Rich_Boy::
	msgbox WaterwayCity_Text_Rich_Boy, MSGBOX_NPC
	end

WaterwayCity_Lass::
	msgbox WaterwayCity_Text_Lass, MSGBOX_NPC
	end

WaterwayCity_Woman_5_2::
	msgbox WaterwayCity_Text_Woman_5_2, MSGBOX_NPC
	end

WaterwayCity_School_Kid_M::
	msgbox WaterwayCity_Text_School_Kid_M, MSGBOX_NPC
	end

WaterwayCity_Man_4::
	msgbox WaterwayCity_Text_Man_4, MSGBOX_NPC
	end

WaterwayCity_PokeFan_M::
	msgbox WaterwayCity_Text_PokeFan_M, MSGBOX_NPC
	end

WaterwayCity_Gentleman::
	msgbox WaterwayCity_Text_Gentleman, MSGBOX_NPC
	end

WaterwayCity_Running_Triathlete_F::
	msgbox WaterwayCity_Text_Running_Triathlete_F, MSGBOX_NPC
	end

WaterwayCity_Man_1_2::
	msgbox WaterwayCity_Text_Man_1_2, MSGBOX_NPC
	end

WaterwayCity_Fisherman::
	msgbox WaterwayCity_Text_Fisherman, MSGBOX_NPC
	end

WaterwayCity_Youngster::
	msgbox WaterwayCity_Text_Youngster, MSGBOX_NPC
	end

WaterwayCity_Fat_Man::
	msgbox WaterwayCity_Text_Fat_Man, MSGBOX_NPC
	end

WaterwayCity_PokeFan_M_2::
	msgbox WaterwayCity_Text_PokeFan_M_2, MSGBOX_NPC
	end

WaterwayCity_Little_Girl::
	msgbox WaterwayCity_Text_Little_Girl, MSGBOX_NPC
	end

WaterwayCity_Girl_2_2::
	msgbox WaterwayCity_Text_Girl_2_2, MSGBOX_NPC
	end

WaterwayCity_Mart_Employee_2::
	msgbox WaterwayCity_Text_Mart_Employee_2, MSGBOX_NPC
	end

WaterwayCity_Mart_Employee_3::
	msgbox WaterwayCity_Text_Mart_Employee_3, MSGBOX_NPC
	end

WaterwayCity_Mart_Employee_4::
	msgbox WaterwayCity_Text_Mart_Employee_4, MSGBOX_NPC
	end

WaterwayCity_Mart_Employee_5::
	msgbox WaterwayCity_Text_Mart_Employee_5, MSGBOX_NPC
	end

WaterwayCity_Text_BlackBelt:

WaterwayCity_Text_Cameraman:

WaterwayCity_Text_Cook:

WaterwayCity_Text_Fat_Man:

WaterwayCity_Text_Fisherman:

WaterwayCity_Text_Gentleman:

WaterwayCity_Text_Girl_1:

WaterwayCity_Text_Girl_2:

WaterwayCity_Text_Girl_2_2:

WaterwayCity_Text_Girl_3:

WaterwayCity_Text_Lass:

WaterwayCity_Text_Little_Girl:

WaterwayCity_Text_Man_1:

WaterwayCity_Text_Man_1_2:

WaterwayCity_Text_Man_4:

WaterwayCity_Text_Mart_Employee_1:

WaterwayCity_Text_Mart_Employee_2:

WaterwayCity_Text_Mart_Employee_3:

WaterwayCity_Text_Mart_Employee_4:

WaterwayCity_Text_Mart_Employee_5:

WaterwayCity_Text_Old_Man:

WaterwayCity_Text_Old_Woman:

WaterwayCity_Text_PokeFan_F_1:

WaterwayCity_Text_PokeFan_F_2:

WaterwayCity_Text_PokeFan_M:

WaterwayCity_Text_PokeFan_M_2:

WaterwayCity_Text_Rich_Boy:

WaterwayCity_Text_Running_Triathlete_F:

WaterwayCity_Text_Sailor:

WaterwayCity_Text_School_Kid_M:

WaterwayCity_Text_Woman_4:

WaterwayCity_Text_Woman_5_1:

WaterwayCity_Text_Woman_5_2:

WaterwayCity_Text_Youngster:
