PinleafTown_House1_MapScripts::
	.byte 0

PinleafTown_House1_Old_Man::
	msgbox PinleafTown_House1_Text_Old_Man, MSGBOX_NPC
	end

PinleafTown_House1_Old_Woman::
	msgbox PinleafTown_House1_Text_Old_Woman, MSGBOX_NPC
	end

PinleafTown_House1_Text_Old_Man:
	.string "I am so proud of my son.\p"
	.string "I only worry that Mr. Mowell works him\n"
	.string "too hard…$"

PinleafTown_House1_Text_Old_Woman:
	.string "My husband and I have lived and worked\n"
	.string "the land in Pinleaf for 60 years now.\p"
	.string "Now that we've retired, it's our son's\n"
	.string "turn to take to the fields!$"
