SunriseTown_House2_MapScripts::
	.byte 0

SunriseTown_House2_Woman::
	msgbox SunriseTown_House2_Text_Woman, MSGBOX_NPC
	end

SunriseTown_House2_Nerd::
	msgbox SunriseTown_House2_Text_Nerd, MSGBOX_NPC
	end

SunriseTown_House2_Text_Woman:
	.string "{COLOR}{RED}The only possible way to tame a Pokémon\n"
	.string "is to catch it using a Poké Ball.\p"
	.string "A wild Pidgey attacked my son yesterday\n"
	.string "in Route 1 and he had to run because he\l"
	.string "didn't have any Poké Balls to catch it.\p"
	.string "I wonder if it's still lurking there…$"

SunriseTown_House2_Text_Nerd:
	.string "{COLOR}{BLUE}The region of Tenjo was once so\n"
	.string "peaceful and secure.\p"
	.string "Pokémon used to live in harmony with\n"
	.string "humans and things were never this bad.\p"
	.string "It has only been in recent years that\n"
	.string "Pokémon have begun to attack humans,\l"
	.string "seemingly out of nowhere.\p"
	.string "Maybe the Tenjo Government has put\n"
	.string "something in the air…$"
