Route1_EventScript_ItemPotion::
	finditem ITEM_POTION
	end

SunriseTown_EventScript_ItemPokeBall::
	finditem ITEM_POKE_BALL
	end

Route2_EventScript_ItemPokeBall::
	finditem ITEM_POKE_BALL
	end

Route2_EventScript_ItemPotion::
	finditem ITEM_POTION
	end

UnionCity_EventScript_ItemPokeBall::
	finditem ITEM_POKE_BALL
	end

Route4_EventScript_ItemPokeBall::
	finditem ITEM_POKE_BALL
	end

Route4_EventScript_ItemSuperRepel::
	finditem ITEM_SUPER_REPEL
	end

AnheimTown_EventScript_ItemHPUp::
	finditem ITEM_HP_UP
	end

AnheimTown_EventScript_ItemEther::
	finditem ITEM_ETHER
	end

Route4_EventScript_ItemPPUp::
	finditem ITEM_PP_UP
	end

Route4_EventScript_ItemPotion::
	finditem ITEM_POTION
	end

Route6_EventScript_ItemPotion::
	finditem ITEM_POTION
	end

Route4_EventScript_ItemParalyzeHeal::
	finditem ITEM_PARALYZE_HEAL
	end

Route4_EventScript_ItemXAccuracy::
	finditem ITEM_X_ACCURACY
	end

PinleafTown_EventScript_ItemMaxRevive::
	finditem ITEM_MAX_REVIVE
	end

Route5_EventScript_ItemEXPShare::
	finditem ITEM_EXP_SHARE
	end

Route5_EventScript_ItemGreatBall::
	finditem ITEM_GREAT_BALL
	end

Route5_EventScript_ItemSuperPotion::
	finditem ITEM_SUPER_POTION
	end

HighwindVillage_EventScript_ItemSodaPop::
	finditem ITEM_SODA_POP
	end

Route5_EventScript_ItemRepeatBall::
	finditem ITEM_REPEAT_BALL
	end

Route113_EventScript_ItemMaxEther:: @ 8290DDC
	finditem ITEM_MAX_ETHER
	end

Route6_EventScript_ItemProtein::
	finditem ITEM_PROTEIN
	end

Route113_EventScript_ItemHyperPotion:: @ 8290DF6
	finditem ITEM_HYPER_POTION
	end

Route6_EventScript_ItemEverstone::
	finditem ITEM_EVERSTONE
	end

Route6_EventScript_ItemFullHeal::
	finditem ITEM_FULL_HEAL
	end

Route3_EventScript_ItemLuxuryBall::
	finditem ITEM_LUXURY_BALL
	end

Route6_EventScript_ItemTimerBall::
	finditem ITEM_TIMER_BALL
	end

Route6_EventScript_ItemRepel::
	finditem ITEM_REPEL
	end

Route6_EventScript_ItemRareCandy::
	finditem ITEM_RARE_CANDY
	end

Route115_EventScript_ItemGreatBall:: @ 8290E51
	finditem ITEM_GREAT_BALL
	end

Route115_EventScript_ItemHealPowder:: @ 8290E5E
	finditem ITEM_HEAL_POWDER
	end

Route115_EventScript_ItemPPUp:: @ 8290E6B
	finditem ITEM_PP_UP
	end

Route5_EventScript_ItemSuperRepel::
	finditem ITEM_SUPER_REPEL
	end

Route6_EventScript_ItemRepeatBall::
	finditem ITEM_REPEAT_BALL
	end

Route6_EventScript_ItemPotion2::
	finditem ITEM_POTION
	end

Route7_EventScript_ItemFullHeal::
	finditem ITEM_FULL_HEAL
	end

Route116_EventScript_ItemPotion:: @ 8290EAC
	finditem ITEM_POTION
	end

Route7_EventScript_ItemMaxEther::
	finditem ITEM_MAX_ETHER
	end

Route7_EventScript_ItemHyperPotion::
	finditem ITEM_HYPER_POTION
	end

Route118_EventScript_ItemHyperPotion:: @ 8290ED3
	finditem ITEM_HYPER_POTION
	end

Route7_EventScript_ItemCarbos:: 
	finditem ITEM_CARBOS
	end

Route8_EventScript_ItemTM27::
	finditem ITEM_TM27
	end

Route8_EventScript_ItemXAttack::
	finditem ITEM_X_ATTACK
	end

Route9_EventScript_ItemUltraBall::
	finditem ITEM_ULTRA_BALL
	end

Route9_EventScript_ItemFullHeal::
	finditem ITEM_FULL_HEAL
	end

Route9_EventScript_ItemSuperPotion::
	finditem ITEM_SUPER_POTION
	end

RockfallCaveInterlink_EventScript_ItemSuperPotion::
	finditem ITEM_SUPER_POTION
	end

PinleafTown_EventScript_ItemElixir::
	finditem ITEM_ELIXIR
	end

Route10_EventScript_ItemRepel:: 
	finditem ITEM_REPEL
	end

Route10_EventScript_ItemEther:: 
	finditem ITEM_ETHER
	end

Route120_EventScript_ItemHyperPotion:: @ 8290F62
	finditem ITEM_HYPER_POTION
	end

Route120_EventScript_ItemNestBall:: @ 8290F6F
	finditem ITEM_NEST_BALL
	end

Route120_EventScript_ItemRevive:: @ 8290F7C
	finditem ITEM_REVIVE
	end

Route121_EventScript_ItemCarbos:: @ 8290F89
	finditem ITEM_CARBOS
	end

Route121_EventScript_ItemRevive:: @ 8290F96
	finditem ITEM_REVIVE
	end

Route121_EventScript_ItemZinc:: @ 8290FA3
	finditem ITEM_ZINC
	end

Route10_EventScript_ItemRevive::
	finditem ITEM_REVIVE
	end

Route10_EventScript_ItemPotion::
	finditem ITEM_POTION
	end

Route123_EventScript_ItemUltraBall:: @ 8290FBD
	finditem ITEM_ULTRA_BALL
	end

Route123_EventScript_ItemElixir:: @ 8290FCA
	finditem ITEM_ELIXIR
	end

Route123_EventScript_ItemPPUp:: @ 8290FD7
	finditem ITEM_PP_UP
	end

Route123_EventScript_ItemRevivalHerb:: @ 8290FE4
	finditem ITEM_REVIVAL_HERB
	end

Route124_EventScript_ItemRedShard:: @ 8290FF1
	finditem ITEM_RED_SHARD
	end

Route124_EventScript_ItemBlueShard:: @ 8290FFE
	finditem ITEM_BLUE_SHARD
	end

Route124_EventScript_ItemYellowShard:: @ 829100B
	finditem ITEM_YELLOW_SHARD
	end

Route125_EventScript_ItemBigPearl:: @ 8291018
	finditem ITEM_BIG_PEARL
	end

Route126_EventScript_ItemGreenShard:: @ 8291025
	finditem ITEM_GREEN_SHARD
	end

NorthstarCity_EventScript_ItemNestBall::
	finditem ITEM_NEST_BALL
	end

AnheimForest_EventScript_ItemFullHeal::
	finditem ITEM_FULL_HEAL
	end

Route127_EventScript_ItemRareCandy:: @ 829104C
	finditem ITEM_RARE_CANDY
	end

AnheimForest_EventScript_ItemPokeBall::
	finditem ITEM_POKE_BALL
	end

Route132_EventScript_ItemProtein:: @ 8291066
	finditem ITEM_PROTEIN
	end

AnheimForest_EventScript_ItemPotion::
	finditem ITEM_POTION
	end

Route133_EventScript_ItemStarPiece:: @ 8291080
	finditem ITEM_STAR_PIECE
	end

AnheimForest_EventScript_ItemAntidote::
	finditem ITEM_ANTIDOTE
	end

Route134_EventScript_ItemCarbos:: @ 829109A
	finditem ITEM_CARBOS
	end

Route134_EventScript_ItemStarPiece:: @ 82910A7
	finditem ITEM_STAR_PIECE
	end

AnheimForest_EventScript_ItemNestBall::
	finditem ITEM_NEST_BALL
	end

AnheimForest_EventScript_ItemGreatBall::
	finditem ITEM_GREAT_BALL
	end

MauvilleCity_EventScript_ItemXSpeed:: @ 82910CE
	finditem ITEM_X_SPEED
	end

RockfallCave_1F_EventScript_ItemPokeBall::
	finditem ITEM_POKE_BALL
	end

SnowdriftForest_EventScript_ItemRevive::
	finditem ITEM_REVIVE
	end

SnowdriftForest_EventScript_ItemTimerBall::
	finditem ITEM_TIMER_BALL
	end

PetalburgWoods_EventScript_ItemXAttack:: @ 8291102
	finditem ITEM_X_ATTACK
	end

PetalburgWoods_EventScript_ItemGreatBall:: @ 829110F
	finditem ITEM_GREAT_BALL
	end

PetalburgWoods_EventScript_ItemEther:: @ 829111C
	finditem ITEM_ETHER
	end

PetalburgWoods_EventScript_ItemParalyzeHeal:: @ 8291129
	finditem ITEM_PARALYZE_HEAL
	end

TamarokTunnels_EventScript_ItemXAttack::
	finditem ITEM_X_ATTACK
	end

TamarokTunnels_EventScript_ItemTM06::
	finditem ITEM_TM06
	end

TamarokTunnels_EventScript_ItemRevive::
	finditem ITEM_REVIVE
	end

TamarokTunnels_EventScript_ItemNeverMeltIce::
	finditem ITEM_NEVER_MELT_ICE
	end

RockfallCave_B1F_EventScript_ItemEscapeRope::
	finditem ITEM_ESCAPE_ROPE
	end

RockfallCave_B1F_EventScript_ItemTM31::
	finditem ITEM_TM31
	end

JaggedPass_EventScript_ItemBurnHeal:: @ 8291184
	finditem ITEM_BURN_HEAL
	end

FieryPath_EventScript_ItemFireStone:: @ 8291191
	finditem ITEM_FIRE_STONE
	end

FieryPath_EventScript_ItemTM06:: @ 829119E
	finditem ITEM_TM06
	end

SnowdriftForest_EventScript_ItemTM03::
	finditem ITEM_TM03
	end

SteepRavine_EventScript_ItemItemfinder::
	finditem ITEM_DOWSING_MACHINE
	end

SteepRavine_EventScript_ItemPPUp::
	finditem ITEM_PP_UP
	end

SteepRavine_EventScript_ItemHPUP::
	finditem ITEM_HP_UP
	end

MeteorFalls_B1F_2R_EventScript_ItemTM02:: @ 82911DF
	finditem ITEM_TM02
	end

NewMauville_Inside_EventScript_ItemUltraBall:: @ 82911EC
	finditem ITEM_ULTRA_BALL
	end

NewMauville_Inside_EventScript_ItemEscapeRope:: @ 82911F9
	finditem ITEM_ESCAPE_ROPE
	end

NewMauville_Inside_EventScript_ItemThunderStone:: @ 8291206
	finditem ITEM_THUNDER_STONE
	end

NewMauville_Inside_EventScript_ItemFullHeal:: @ 8291213
	finditem ITEM_FULL_HEAL
	end

NewMauville_Inside_EventScript_ItemParalyzeHeal:: @ 8291220
	finditem ITEM_PARALYZE_HEAL
	end

AbandonedShip_Rooms_1F_EventScript_ItemHarborMail:: @ 829122D
	finditem ITEM_HARBOR_MAIL
	end

AbandonedShip_Rooms_B1F_EventScript_ItemEscapeRope:: @ 829123A
	finditem ITEM_ESCAPE_ROPE
	end

AbandonedShip_Rooms2_B1F_EventScript_ItemDiveBall:: @ 8291247
	finditem ITEM_DIVE_BALL
	end

AbandonedShip_Room_B1F_EventScript_ItemTM13:: @ 8291254
	finditem ITEM_TM13
	end

AbandonedShip_Rooms2_1F_EventScript_ItemRevive:: @ 8291261
	finditem ITEM_REVIVE
	end

AbandonedShip_CaptainsOffice_EventScript_ItemStorageKey:: @ 829126E
	finditem ITEM_STORAGE_KEY
	end

AbandonedShip_HiddenFloorRooms_EventScript_ItemLuxuryBall:: @ 829127B
	finditem ITEM_LUXURY_BALL
	end

AbandonedShip_HiddenFloorRooms_EventScript_ItemScanner:: @ 8291288
	finditem ITEM_SCANNER
	end

AbandonedShip_HiddenFloorRooms_EventScript_ItemWaterStone:: @ 8291295
	finditem ITEM_WATER_STONE
	end

AbandonedShip_HiddenFloorRooms_EventScript_ItemTM18:: @ 82912A2
	finditem ITEM_TM18
	end

ScorchedSlab_EventScript_ItemTM11:: @ 82912AF
	finditem ITEM_TM11
	end

SafariZone_Northwest_EventScript_ItemTM22:: @ 82912BC
	finditem ITEM_TM22
	end

SafariZone_North_EventScript_ItemCalcium:: @ 82912C9
	finditem ITEM_CALCIUM
	end

SafariZone_Southwest_EventScript_ItemMaxRevive:: @ 82912D6
	finditem ITEM_MAX_REVIVE
	end

SafariZone_Northeast_EventScript_ItemNugget:: @ 82912E3
	finditem ITEM_NUGGET
	end

SafariZone_Southeast_EventScript_ItemBigPearl:: @ 82912F0
	finditem ITEM_BIG_PEARL
	end

MtPyre_2F_EventScript_ItemUltraBall:: @ 82912FD
	finditem ITEM_ULTRA_BALL
	end

MtPyre_3F_EventScript_ItemSuperRepel:: @ 829130A
	finditem ITEM_SUPER_REPEL
	end

MtPyre_4F_EventScript_ItemSeaIncense:: @ 8291317
	finditem ITEM_SEA_INCENSE
	end

TamarokTunnels_EventScript_ItemTM07::
	finditem ITEM_TM07
	end

MtPyre_6F_EventScript_ItemTM30:: @ 8291331
	finditem ITEM_TM30
	end

MtPyre_Exterior_EventScript_ItemMaxPotion:: @ 829133E
	finditem ITEM_MAX_POTION
	end

MtPyre_Exterior_EventScript_ItemTM48:: @ 829134B
	finditem ITEM_TM48
	end

AquaHideout_B1F_EventScript_ItemMasterBall:: @ 8291358
	finditem ITEM_MASTER_BALL
	end

AquaHideout_B1F_EventScript_ItemNugget:: @ 8291365
	finditem ITEM_NUGGET
	end

AquaHideout_B1F_EventScript_ItemMaxElixir:: @ 8291372
	finditem ITEM_MAX_ELIXIR
	end

AquaHideout_B2F_EventScript_ItemNestBall:: @ 829137F
	finditem ITEM_NEST_BALL
	end

AquaHideout_B2F_EventScript_ItemMasterBall:: @ 829138C
	finditem ITEM_MASTER_BALL      // Unused
	end

LaveriaCity_EventScript_ItemNugget::
	finditem ITEM_NUGGET
	end

Route119_EventScript_ItemMaxElixir:: @ 82913A6
	finditem ITEM_MAX_ELIXIR
	end

Route119_EventScript_ItemNestBall:: @ 82913B3
	finditem ITEM_NEST_BALL
	end

ShoalCave_LowTideEntranceRoom_EventScript_ItemBigPearl:: @ 82913C0
	finditem ITEM_BIG_PEARL
	end

ShoalCave_LowTideInnerRoom_EventScript_ItemRareCandy:: @ 82913CD
	finditem ITEM_RARE_CANDY
	end

ShoalCave_LowTideStairsRoom_EventScript_ItemIceHeal:: @ 82913DA
	finditem ITEM_ICE_HEAL
	end

ShoalCave_LowTideIceRoom_EventScript_ItemTM07:: @ 82913E7
	finditem ITEM_TM07
	end

ShoalCave_LowTideIceRoom_EventScript_ItemNeverMeltIce:: @ 82913F4
	finditem ITEM_NEVER_MELT_ICE
	end

SeafloorCavern_Room9_EventScript_ItemTM26:: @ 8291401
	finditem ITEM_TM26
	end

Route110_TrickHousePuzzle1_EventScript_ItemOrangeMail:: @ 829140E
	finditem ITEM_ORANGE_MAIL
	end

Route110_TrickHousePuzzle2_EventScript_ItemHarborMail:: @ 829141B
	finditem ITEM_HARBOR_MAIL
	end

Route110_TrickHousePuzzle2_EventScript_ItemWaveMail:: @ 8291428
	finditem ITEM_WAVE_MAIL
	end

Route110_TrickHousePuzzle3_EventScript_ItemShadowMail:: @ 8291435
	finditem ITEM_SHADOW_MAIL
	end

Route110_TrickHousePuzzle3_EventScript_ItemWoodMail:: @ 8291442
	finditem ITEM_WOOD_MAIL
	end

Route110_TrickHousePuzzle4_EventScript_ItemMechMail:: @ 829144F
	finditem ITEM_MECH_MAIL
	end

Route110_TrickHousePuzzle6_EventScript_ItemGlitterMail:: @ 829145C
	finditem ITEM_GLITTER_MAIL
	end

Route110_TrickHousePuzzle7_EventScript_ItemTropicMail:: @ 8291469
	finditem ITEM_TROPIC_MAIL
	end

Route110_TrickHousePuzzle8_EventScript_ItemBeadMail:: @ 8291476
	finditem ITEM_BEAD_MAIL
	end

VictoryRoad_1F_EventScript_ItemMaxElixir:: @ 8291483
	finditem ITEM_MAX_ELIXIR
	end

VictoryRoad_1F_EventScript_ItemPPUp:: @ 8291490
	finditem ITEM_PP_UP
	end

VictoryRoad_B1F_EventScript_ItemTM29:: @ 829149D
	finditem ITEM_TM29
	end

VictoryRoad_B1F_EventScript_ItemFullRestore:: @ 82914AA
	finditem ITEM_FULL_RESTORE
	end

VictoryRoad_B2F_EventScript_ItemFullHeal:: @ 82914B7
	finditem ITEM_FULL_HEAL
	end

ArtisanCave_B1F_EventScript_ItemHPUp:: @ 82914C4
	finditem ITEM_HP_UP
	end

ArtisanCave_1F_EventScript_ItemCarbos:: @ 82914D1
	finditem ITEM_CARBOS
	end

MagmaHideout_1F_EventScript_ItemRareCandy:: @ 82914DE
	finditem ITEM_RARE_CANDY
	end

MagmaHideout_2F_2R_EventScript_MaxElixir:: @ 82914EB
	finditem ITEM_MAX_ELIXIR
	end

MagmaHideout_2F_2R_EventScript_ItemFullRestore:: @ 82914F8
	finditem ITEM_FULL_RESTORE
	end

MagmaHideout_3F_1R_EventScript_ItemNugget:: @ 8291505
	finditem ITEM_NUGGET
	end

MagmaHideout_3F_2R_EventScript_ItemPPMax:: @ 8291512
	finditem ITEM_PP_MAX
	end

MagmaHideout_4F_EventScript_MaxRevive:: @ 829151F
	finditem ITEM_MAX_REVIVE
	end

MagmaHideout_3F_3R_EventScript_ItemEscapeRope:: @ 829152C
	finditem ITEM_ESCAPE_ROPE
	end
