Common_Movement_QuestionMark: @ 8272596
	emote_question_mark
	step_end

Common_Movement_ExclamationMark: @ 8272598
	emote_exclamation_mark
	step_end

Common_Movement_Heart:
	emote_heart
	step_end

Common_Movement_Delay48: @ 827259A
	delay_16
	delay_16
	delay_16
	step_end

Common_Movement_FacePlayer: @ 827259E
	face_player
	step_end

Common_Movement_FaceAwayPlayer: @ 82725A0
	face_away_player
	step_end

Common_Movement_FaceOriginalDirection: @ 82725A2
	face_original_direction
	step_end

Common_Movement_WalkInPlaceFasterLeft: @ 82725A4
	walk_in_place_faster_left
	step_end

Common_Movement_WalkInPlaceFasterUp: @ 82725A6
	walk_in_place_faster_up
	step_end

Common_Movement_WalkInPlaceFasterRight: @ 82725A8
	walk_in_place_faster_right
	step_end

Common_Movement_WalkInPlaceFasterDown: @ 82725AA
	walk_in_place_faster_down
	step_end

Common_Movement_FaceRight: @ 82725AC
	face_right
	step_end

Common_Movement_FaceLeft: @ 82725AE
	face_left
	step_end

Common_Movement_FaceDown: @ 82725B0
	face_down
	step_end

Common_Movement_FaceUp: @ 82725B2
	face_up
	step_end

Common_Movement_WalkInPlaceDown: @ 82725B4
	walk_in_place_down
	step_end

Common_Movement_WalkInPlaceLeft: @ 82725B6
	walk_in_place_left
	step_end

Common_Movement_WalkInPlaceRight: @ 82725B8
	walk_in_place_right
	step_end

Common_Movement_WalkInPlaceSlowDown:
	walk_in_place_slow_down
	step_end

Common_Movement_WalkInPlaceSlowLeft:
	walk_in_place_slow_left
	step_end

Common_Movement_WalkInPlaceSlowRight:
	walk_in_place_slow_right
	step_end

Common_Movement_WalkInPlaceSlowUp:
	walk_in_place_slow_up
	step_end

Common_Movement_WalkLeftFaster:
	walk_faster_left
	step_end

Common_Movement_WalkRightFaster:
	walk_faster_right
	step_end

Common_Movement_WalkRightSlow:
	walk_slow_right
	step_end

Common_Movement_WalkLeft:
	walk_left
	step_end

Common_Movement_WalkRight:
	walk_right
	step_end

Common_Movement_WalkUp6: @ 82725BA
	walk_up
	walk_up
	walk_up
	walk_up
	walk_up
	walk_up
	step_end

Common_Movement_WalkUp4: @ 82725C1
	walk_up
	walk_up
	walk_up
	walk_up
	step_end

Common_Movement_Delay32: @ 82725C6
	delay_16
	delay_16
	step_end

Common_Movement_WalkUp: @ 82725C9
	walk_up
	step_end
