NorthstarCity_Apartments_MapScripts::
	.byte 0

NorthstarCity_Apartments_Little_Boy::
	msgbox NorthstarCity_Apartments_Text_Little_Boy, MSGBOX_NPC
	end

NorthstarCity_Apartments_Father::
	msgbox NorthstarCity_Apartments_Text_Father, MSGBOX_NPC
	end

NorthstarCity_Apartments_Lass::
	msgbox NorthstarCity_Apartments_Text_Lass, MSGBOX_NPC
	end

NorthstarCity_Apartments_Meowth::
	msgbox NorthstarCity_Apartments_Text_Meowth, MSGBOX_NPC
	end

NorthstarCity_Apartments_Picnicker::
	msgbox NorthstarCity_Apartments_Text_Picnicker, MSGBOX_NPC
	end

NorthstarCity_Apartments_Chef::
	msgbox NorthstarCity_Apartments_Text_Chef, MSGBOX_NPC
	end

NorthstarCity_Apartments_Reporter::
	msgbox NorthstarCity_Apartments_Text_Reporter, MSGBOX_NPC
	end

NorthstarCity_Apartments_Fat_Guy::
	msgbox NorthstarCity_Apartments_Text_Fat_Guy, MSGBOX_NPC
	end

NorthstarCity_Apartments_Old_Man::
	msgbox NorthstarCity_Apartments_Text_Old_Man, MSGBOX_NPC
	end

NorthstarCity_Apartments_Sailor::
	msgbox NorthstarCity_Apartments_Text_Sailor, MSGBOX_NPC
	end	

NorthstarCity_Apartments_Expert_M::
	msgbox NorthstarCity_Apartments_Text_Expert_M, MSGBOX_NPC
	end

NorthstarCity_Apartments_Expert_F::
	msgbox NorthstarCity_Apartments_Text_Expert_F, MSGBOX_NPC
	end

NorthstarCity_Apartments_Hiker::
	msgbox NorthstarCity_Apartments_Text_Hiker, MSGBOX_NPC
	end

NorthstarCity_Apartments_Text_Little_Boy:
	.string "{COLOR}{BLUE}I spend a lot of time studying because\n"
	.string "it's snowing all the time outside.\p"
	.string "I wonder if students in colder\n"
	.string "climates get better grades…$"

NorthstarCity_Apartments_Text_Father:
	.string "{COLOR}{BLUE}I'm a manager at a construction\n"
	.string "company.\p"
	.string "Guess who built this apartment\n"
	.string "complex?!\p"
	.string "Well… it wasn't me.\n"
	.string "But I sure would've liked it to be.$"

NorthstarCity_Apartments_Text_Lass:
	.string "{COLOR}{RED}I love my Meowth.\n"
	.string "She always keeps me company.\p"
	.string "I expect to grow old with her!$"

NorthstarCity_Apartments_Text_Meowth:

NorthstarCity_Apartments_Text_Picnicker:
	.string "{COLOR}{RED}I have a huge fear of bugs…\p"
	.string "Thankfully, they don't usually show\n"
	.string "up in these climates!$"

NorthstarCity_Apartments_Text_Chef:
	.string "{COLOR}{BLUE}The best job is the one I have: Ship's\n"
	.string "Cook.\p"
	.string "I go on voyages to exotic places\n"
	.string "all the time and get paid for it.\p"
	.string "Plus, I love cooking!$"

NorthstarCity_Apartments_Text_Reporter:
	.string "{COLOR}{BLUE}I used to work at the TV Station as a\n"
	.string "journalist, but I called it quits.\l"
	.string "Now, I work as an independent.\p"
	.string "I have no job security, but I couldn't\n"
	.string "be happier, to be honest.$"

NorthstarCity_Apartments_Text_Fat_Guy:
	.string "{COLOR}{BLUE}Sometimes I book a ticket to Laveria\n"
	.string "City, just to get access to the\l"
	.string "all-you-can-eat buffet.\p"
	.string "I can't resist that special sauce they\n"
	.string "put on the chicken! Mmmmh…$"

NorthstarCity_Apartments_Text_Old_Man:
	.string "Looking through the windows at the\n"
	.string "city's skyscrapers…\p"
	.string "Watching the snow fall ever so\n"
	.string "lightly…\p"
	.string "Now, that's a good retirement plan,\n"
	.string "if I've ever heard of any.$"

NorthstarCity_Apartments_Text_Sailor:
	.string "{COLOR}{BLUE}Lately, shady characters have been\n"
	.string "showing up in the docks where I work.\p"
	.string "I don't like 'em.\n"
	.string "I don't like 'em at all…$"

NorthstarCity_Apartments_Text_Expert_M:
	.string "My wife and I used to train Pokémon in\n"
	.string "our youth.\p"
	.string "We liked to challenge other Trainers,\n"
	.string "like you, to double battles!$"

NorthstarCity_Apartments_Text_Expert_F:
	.string "I wish my Pokémon were still with\n"
	.string "us…\p"
	.string "Age can be a terrible thing.$"

NorthstarCity_Apartments_Text_Hiker:
	.string "In the good ol' days, I used to enjoy\n"
	.string "hiking around Mt. Tamarok.\p"
	.string "One time hiking, I got caught in a\n"
	.string "blistering snowstorm at sub-zero\l"
	.string "temperatures.\p"
	.string "Slowly, I noticed a dark silhoutte\n"
	.string "emerge from the mist ahead.\p"
	.string "It looked like a Piloswine.\n"
	.string "A hungry and an angry one.\p"
	.string "As I got closer, I realized it was\n"
	.string "just a large doll, lodged in the snow.\p"
	.string "Today, I still wonder who would place\n"
	.string "such a thing there…$"
