WaterwayCity_PortHouse2_MapScripts::
	.byte 0

WaterwayCity_PortHouse2_Sailor::
	msgbox WaterwayCity_PortHouse2_Text_Sailor, MSGBOX_NPC
	end

WaterwayCity_PortHouse2_Man::
	msgbox WaterwayCity_PortHouse2_Text_Man, MSGBOX_NPC
	end

WaterwayCity_PortHouse2_Text_Sailor:
	.string "{COLOR}{BLUE}Ah, this region?\n"
	.string "It's full of wonders, kid.\p"
	.string "I've sailed from shore to shore, seen\n"
	.string "islands untouched by human hands, and\l"
	.string "even witnessed legendary Pokémon.\p"
	.string "But the thing that sticks with me\n"
	.string "the most?\p"
	.string "The mysterious fog-covered island,\n"
	.string "Aetheris.\p"
	.string "They say no map shows its true\n"
	.string "location, and only a few sailors have\l"
	.string "returned with tales of oddd markings\l"
	.string "in the sand.$"

WaterwayCity_PortHouse2_Text_Man:
	.string "{COLOR}{BLUE}I once took a journey to the volcanic\n"
	.string "part of Tenjo, down south.\p"
	.string "The ground was hot beneath my feet,\n"
	.string "and the air was thick with ash.\p"
	.string "But the Pokémon there…\n"
	.string "They're like nothing else.\p"
	.string "Fire-types as fierce as the volcano\n"
	.string "itself!\p"
	.string "If you're brave enough to go, I'd say\n"
	.string "you ought to pack many Burn Heals.$"
