LaveriaCity_MapScripts::
	.byte 0

LaveriaCity_Sign::
	msgbox LaveriaCity_Text_Sign, MSGBOX_SIGN
	end

LaveriaCity_Sign_Route::
	msgbox LaveriaCity_Text_Sign_Route, MSGBOX_SIGN
	end

LaveriaCity_Sign_Locked::
	msgbox LaveriaCity_Text_Sign_Locked, MSGBOX_SIGN
	end

LaveriaCity_Little_Boy::
	msgbox LaveriaCity_Text_Little_Boy, MSGBOX_NPC
	end

LaveriaCity_Big_Sister::
	msgbox LaveriaCity_Text_Big_Sister, MSGBOX_NPC
	end

LaveriaCity_Boy_1::
	msgbox LaveriaCity_Text_Boy_1, MSGBOX_NPC
	end

LaveriaCity_Man::
	msgbox LaveriaCity_Text_Man, MSGBOX_NPC
	end

LaveriaCity_Boy_2::
	msgbox LaveriaCity_Text_Boy_2, MSGBOX_NPC
	end

LaveriaCity_PokeFan::
	msgbox LaveriaCity_Text_PokeFan, MSGBOX_NPC
	end

LaveriaCity_Old_Man::
	msgbox LaveriaCity_Text_Old_Man, MSGBOX_NPC
	end

LaveriaCity_Text_Sign:
	.string "Welcome to Laveria City\p"
	.string "The place for frosty mornings and\n"
	.string "toasty mugs!$"

LaveriaCity_Text_Sign_Route:
	.string "{LEFT_ARROW} Route 7$"

LaveriaCity_Text_Sign_Locked:
	.string "The door is locked…$"

LaveriaCity_Text_Little_Boy:
	.string "{COLOR}{BLUE}My big sister says someone with Surf\n"
	.string "can get to that island off the coast.\p"
	.string "I wish I had a Pokémon that knew Surf…$"

LaveriaCity_Text_Big_Sister:
	.string "{COLOR}{RED}During the night, I saw something\n"
	.string "glitter in the ocean.\p"
	.string "It was coming from the direction of\n"
	.string "that island off the coast of the city.\p"
	.string "What could it have been?$"

LaveriaCity_Text_Boy_1:
	.string "{COLOR}{BLUE}See that item across the fence?\n"
	.string "I've been trying to get it forever.\p"
	.string "The fence is too high and there's no\n"
	.string "way to get there by the frozen pond.\p"
	.string "Won't the pond ever defrost?\n"
	.string "Is it always winter in this city?$"

LaveriaCity_Text_Man:
	.string "{COLOR}{BLUE}This frozen pond wasn't always frozen…\p"
	.string "No, it completely froze over as a\n"
	.string "result of this harsh weather.\p"
	.string "Oh, well…\n"
	.string "The ice will eventually defrost!$"

LaveriaCity_Text_Boy_2:
	.string "{COLOR}{BLUE}Jeez! We've been snowed in!\n"
	.string "Again!\p"
	.string "Maybe I should have never moved here\n"
	.string "in the north and sat pretty at Pinleaf\l"
	.string "Town in the warm south…$"

LaveriaCity_Text_PokeFan:
	.string "{COLOR}{RED}I was once a Trainer, like you.\p"
	.string "I even won a couple of tournaments,\n"
	.string "but now I'm retired…\p"
	.string "It's a bit boring here, but at least\n"
	.string "I still have my trusted Pokémon!$"

LaveriaCity_Text_Old_Man:
	.string "Ha!\p"
	.string "Little young Trainer, where do you\n"
	.string "think you are going?\p"
	.string "You think you have what it takes to\n"
	.string "brave the snowstorm in Route 7?$"
