LaveriaCity_House2_MapScripts::
	.byte 0

LaveriaCity_House2_Old_Man::
	msgbox LaveriaCity_House2_Text_Old_Man, MSGBOX_NPC
	end

LaveriaCity_House2_Text_Old_Man:
	.string "As cold as ice she rebuked me.\n"
	.string "Azure eyes would cry frozen tears.\p"
	.string "Pallid, as far as could see, I'd\n"
	.string "lived with her during my fears.\p"
	.string "Then one day she just left me,\n"
	.string "warmth returned, and I was free.$"
