GreendaleVillage_Mart_MapScripts::
	.byte 0

GreendaleVillage_Mart_Fat_Guy::
	msgbox GreendaleVillage_Mart_Text_Fat_Guy, MSGBOX_NPC
	end

GreendaleVillage_Mart_Bug_Catcher::
	msgbox GreendaleVillage_Mart_Text_Bug_Catcher, MSGBOX_NPC
	end

GreendaleVillage_Mart_Text_Fat_Guy:
	.string "{COLOR}{BLUE}Why can't humans eat Rare Candies?\n"
	.string "Like, man, they look so good…$"

GreendaleVillage_Mart_Text_Bug_Catcher:
	.string "{COLOR}{BLUE}I wasted all my Great Balls catching\n"
	.string "Bug-type Pokémon in Anheim Forest.\p"
	.string "I'd better stock up on more!$"
