WaterwayCity_House4_MapScripts::
	.byte 0

WaterwayCity_House4_LittleBoy::
	msgbox WaterwayCity_House4_Text_LittleBoy, MSGBOX_NPC
	end

WaterwayCity_House4_Woman::
	msgbox WaterwayCity_House4_Text_Woman, MSGBOX_NPC
	end

WaterwayCity_House4_Text_LittleBoy:
	.string "{COLOR}{BLUE}My dad is always out fishing, but I\n"
	.string "like staying home with our Poliwag.\p"
	.string "It's fun watching it swim around in\n"
	.string "our little pond.\p"
	.string "Maybe one day I'll go fishing with\n"
	.string "him…$"

WaterwayCity_House4_Text_Woman:
	.string "{COLOR}{RED}Being married to a Fisherman?\n"
	.string "Well, it's definitely an adventure!\p"
	.string "My husband is out on the water from\n"
	.string "dawn till dusk, always chasing after\l"
	.string "the biggest catch.\p"
	.string "Sometimes he's gone for days if he's\n"
	.string "found a good fishing spot.$"
