UnionCity_PokemonCenter_1F_MapScripts::
	.byte 0

UnionCity_PokemonCenter_1F_Old_Man::
	msgbox UnionCity_PokemonCenter_1F_Text_Old_Man, MSGBOX_NPC
	end

UnionCity_PokemonCenter_1F_Girl::
	msgbox UnionCity_PokemonCenter_1F_Text_Girl, MSGBOX_NPC
	end

UnionCity_PokemonCenter_1F_Text_Old_Man:
	.string "Union City…\nHome of the Tenjo Government…\p"
	.string "The government is so out of control.\p"
	.string "It is so bloated and infested with\n"
	.string "fraud, deceit, corruption and total\l"
	.string "abuse of power.\p"
	.string "You'll understand what I'm saying,\n"
	.string "one day…$"

UnionCity_PokemonCenter_1F_Text_Girl:
	.string "{COLOR}{RED}The man next door gave me a TM!\p"
	.string "I used it to teach my Pokémon how to\n"
	.string "bulk up their power!$"
