AnheimTown_PokemonCenter_1F_MapScripts::
	.byte 0

AnheimTown_PokemonCenter_1F_Gentleman::
	msgbox AnheimTown_PokemonCenter_1F_Text_Gentleman, MSGBOX_NPC
	end

AnheimTown_PokemonCenter_1F_Text_Gentleman:
	.string "Peace is a daily, a weekly, a monthly\n"
	.string "process.\p"
	.string "Gradually changing opinions, slowly\n"
	.string "eroding old barriers, quietly building\l"
	.string "new structures.$"
