UnionCity_House3_2F_MapScripts::
	.byte 0

UnionCity_House_2F_MudkipPlushDoll::
	lock
	msgbox UnionCity_House_2F_Text_MudkipPlushie, MSGBOX_DEFAULT
	release
	end

UnionCity_House_2F_PikachuPlushDoll::
	lock
	msgbox UnionCity_House_2F_Text_PikachuPlushie, MSGBOX_DEFAULT
	release
	end

UnionCity_House_2F_TorchicPlushDoll::
	lock
	msgbox UnionCity_House_2F_Text_TorchicPlushie, MSGBOX_DEFAULT
	release
	end

UnionCity_House_2F_TreeckoPlushDoll::
	lock
	msgbox UnionCity_House_2F_Text_TreeckoPlushie, MSGBOX_DEFAULT
	release
	end

UnionCity_House_2F_SkittyPlushDoll::
	lock
	msgbox UnionCity_House_2F_Text_SkittyPlushie, MSGBOX_DEFAULT
	release
	end

UnionCity_House_2F_Text_MudkipPlushie:
	.string "It's a Mudkip plushie!$"

UnionCity_House_2F_Text_PikachuPlushie:
	.string "It's a Pikachu plushie!$"

UnionCity_House_2F_Text_TorchicPlushie:
	.string "It's a Torchic plushie!$"

UnionCity_House_2F_Text_TreeckoPlushie:
	.string "It's a Treecko plushie!$"

UnionCity_House_2F_Text_SkittyPlushie:
	.string "It's a Skitty plushie!$"

